- server/openejb-client/src/main/java/org/apache/openejb/client/Client.java
- server/openejb-client/src/main/java/org/apache/openejb/client/HttpConnectionFactory.java
- server/openejb-client/src/main/java/org/apache/openejb/client/JNDIContext.java
- server/openejb-client/src/main/java/org/apache/openejb/client/JNDIContextAuth.java
- tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/remote/TomEERemoteWebapp.java
> Work in progress - support HTTP authorization header

- examples/javamail/README.md
- maven/tomee-maven-plugin/src/test/java/test/patch/MyMain.java
- maven/tomee-maven-plugin/src/test/java/test/patch/foo/Another.java
- tomee/apache-tomee/src/main/resources/tomee.bat
Signed-off-by: Daniel Cunha danielsoro@apache.org
> TOMEE-2084 - Update files with correct copyright.

- container/openejb-core/src/main/java/org/apache/openejb/dyni/DynamicSubclass.java
- container/openejb-core/src/main/java/org/apache/openejb/resource/AutoConnectionTracker.java
- container/openejb-core/src/main/java/org/apache/openejb/util/proxy/DynamicProxyImplFactory.java
- container/openejb-core/src/main/java/org/apache/openejb/util/proxy/LocalBeanProxyFactory.java
- container/openejb-core/src/test/java/org/apache/openejb/config/ConnectorProxyTest.java
Proposed backport of TOMEE-2082.
> TOMEE-2082 - TOMEE-1908 allow JCA connectors to cast to their connection impl

- pom.xml
HSQLDB 2.3.2 has regression that prevent:
> multiple rows with partial null values could not be inserted in UNIQUE indexes
See http://hsqldb.org/doc/2.0/changelist_2_0.txt 2.3.3 CHANGE_LOG
I would update to latest JRE 6 compatible HSQLDB version (except 2.4.0 that is required JRE 8)
Fixes TOMEE-2155
---
I was not able to run `mvn clean install` completely... I always get a fail on  (even on unmodified `master` branch)
```
[INFO] OpenEJB :: TomEE :: Juli ........................... FAILURE [ 29.728 s]
```
```
[INFO] Running org.apache.tomee.jul.handler.rotating.ArchivingTest
[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 24.324 s <<< FAILURE! - in org.apache.tomee.jul.handler.rotating.ArchivingTest
[ERROR] …
```
> Upgrade HSQLDB to 2.3.5

- container/openejb-core/src/main/java/org/apache/openejb/assembler/classic/JndiEncBuilder.java
- container/openejb-core/src/main/java/org/apache/openejb/core/ivm/naming/MapObjectReference.java
- server/openejb-cxf-rs/src/main/java/org/apache/openejb/server/cxf/rs/Contexts.java
- server/openejb-cxf-rs/src/test/java/org/apache/openejb/server/cxf/rs/ApplicationRsInjectionTest.java
Same as https://github.com/apache/tomee/pull/135 but for TomEE8.
> [TOMEE-2201] NPE when injecting Application for TomEE8

- assembly/openejb-standalone/src/main/conf/README.txt
- itests/openejb-itests-client/src/main/java/org/apache/openejb/test/CorbaTestServer.java
Hi there, 
I wrote this bot based on the top 10 most misspelled english words.
(https://blog.oxforddictionaries.com/2016/08/02/corpus-misspellings/)
The bot queries, forks, clones, fixes and commits but I manually create the PRs.
All the best,
Jimmy
> Fixed Spelling.

- container/openejb-core/src/main/java/org/apache/openejb/util/proxy/LocalBeanProxyFactory.java
Hi,
I wanted to test jdk 11 with tomeee, so I made this patch (borrowed from openwebbeans), maybe you can use it as well (tested on jdk 10 and 11, no class leaking).
Although my knowledge about unsafe and proxies is quite limited, just ditch it if it's not correct.
Best regards,
Vicentee.
> jdk 11 compatibility

- itests/legacy-server/pom.xml
- itests/legacy-server/src/test/java/org/apache/openejb/itest/legacy/LegacyServerTest.java
> fix itests/legacy-server unit tests

- pom.xml
[tomee-7.0.x] [TOMEE-2268] Upgrade CXF to 3.1.8per user request: https://bit.ly/2SGYGm6
> [tomee-7.0.x] [TOMEE-2268] Upgrade CXF to 3.1.8per user request: https://bit.ly/2SGYGm6

- pom.xml
[tomee-7.1.x] [tomee-2268] upgrade cxf to 3.1.8: https://bit.ly/2SGYGm6
> [tomee-7.1.x] [tomee-2268] upgrade cxf to 3.1.8

- examples/mp-metrics-counted/pom.xml
- examples/mp-metrics-counted/src/test/java/org/superbiz/rest/WeatherServiceTest.java
Some fixes done in the current example:
- Fixing payload in test after the fix of a jsonb regression
- Replace Webclient with WebTarget
- Fix to use top level properties with versions
- Better assertion by key type
> TOMEE-2279 - Metrics Counted Example Improvements

- container/openejb-core/src/main/java/org/apache/openejb/assembler/classic/MethodInfoUtil.java
- container/openejb-core/src/main/java/org/apache/openejb/log/logger/Slf4jLogger.java
- container/openejb-core/src/main/java/org/apache/openejb/math/stat/descriptive/DescriptiveStatistics.java
- container/openejb-core/src/main/java/org/apache/openejb/math/stat/descriptive/moment/Kurtosis.java
- container/openejb-core/src/main/java/org/apache/openejb/math/stat/descriptive/moment/Skewness.java
- container/openejb-jee/src/main/java/org/apache/openejb/jee/FacesConfigFlowDefinition.java
- container/openejb-junit/src/main/java/org/apache/openejb/junit/context/OpenEjbTestContext.java
- container/openejb-junit/src/main/java/org/apache/openejb/junit/context/Util.java
- itests/openejb-itests-beans/src/main/java/org/apache/openejb/test/SuperInterceptedBean.java
- itests/openejb-itests-beans/src/main/java/org/apache/openejb/test/entity/bmp/BasicBmp2DataSourcesBean.java
- itests/openejb-itests-beans/src/main/java/org/apache/openejb/test/entity/bmp/RmiIiopBmpBean.java
- itests/openejb-itests-beans/src/main/java/org/apache/openejb/test/interceptor/ClassInterceptor.java
- itests/openejb-itests-beans/src/main/java/org/apache/openejb/test/interceptor/DDInterceptor.java
- itests/openejb-itests-beans/src/main/java/org/apache/openejb/test/interceptor/MethodInterceptor.java
- itests/openejb-itests-beans/src/main/java/org/apache/openejb/test/interceptor/SecondClassInterceptor.java
- itests/openejb-itests-beans/src/main/java/org/apache/openejb/test/interceptor/SuperClassInterceptor.java
- itests/openejb-itests-beans/src/main/java/org/apache/openejb/test/singleton/BeanTxSingletonBean.java
- itests/openejb-itests-beans/src/main/java/org/apache/openejb/test/stateless/BeanTxStatelessBean.java
- itests/openejb-itests-client/src/main/java/org/apache/openejb/test/RiTestServer.java
- server/openejb-server/src/main/java/org/apache/openejb/server/DiscoveryAgent.java
- tomee/apache-tomee/src/main/java/org/apache/tomee/RemoteTomEEEJBContainer.java
- tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/OpenEJBNamingContextListener.java
- tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/OpenEJBNamingResource.java
- tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/TomEEWebappLoader.java
- tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/TomcatLoader.java
- tomee/tomee-juli/src/main/java/org/apache/tomee/jul/formatter/SimpleTomEEFormatter.java
- tomee/tomee-juli/src/main/java/org/apache/tomee/jul/handler/rotating/LocalFileHandler.java
- tomee/tomee-juli/src/test/java/org/apache/tomee/jul/formatter/SimpleTomEEFormatterTest.java
- tomee/tomee-loader/src/main/java/org/apache/tomee/loader/LoaderServlet.java
- tomee/tomee-loader/src/main/java/org/apache/tomee/loader/OpenEJBListener.java
Here are just some of the most visible JavaDoc errors fixed.
> Fixing major JavaDoc errors for Tomee

- docs/activemqresourceadapter-config.md
- docs/comparison.md
- docs/datasource-config.md
- docs/datasource-configuration-by-creator.md
- docs/deploying-in-tomee.md
- docs/ejbd-transport.md
- docs/jpa-concepts.md
- docs/jpa-usage.md
- docs/openjpa.md
- docs/persistence-context.md
- docs/persistence-unit-ref.md
- docs/tomee-and-hibernate.md
- docs/tomee-directory-structure.md
- docs/tomee-webapp.md
First stab at editing the documentation index groups.  Correcting typo for General Information
> documentation updates

- container/openejb-core/src/main/java/org/apache/openejb/cli/Bootstrap.java
- itests/failover/src/test/java/org/apache/openejb/itest/failover/RandomConnectionStrategyTest.java
- tomee/apache-tomee/src/test/java/org/apache/tomee/TomEECliIT.java
These changes should resolve the itest failures, but Daniel's new additional tests still pass.
> TOMEE-2322 fix build issues

- tomee/tomee-embedded/src/main/java/org/apache/tomee/embedded/Main.java
https://github.com/apache/tomee/commit/469e7cb94c52d06102622bd0f54e0bf1a6a470ff#diff-03949e036a3ccddcf99c00ded5317c66R261
Simple fix.
> TOMEE-2325 - Fix checking for INTERACTIVE option in embedded Main

- server/openejb-multicast/src/main/java/org/apache/openejb/server/discovery/MulticastDiscoveryAgent.java
- server/openejb-multicast/src/main/java/org/apache/openejb/server/discovery/MultipointDiscoveryAgent.java
- server/openejb-multicast/src/main/java/org/apache/openejb/server/discovery/MultipointServer.java
- server/openejb-webservices/src/main/java/org/apache/openejb/server/webservices/WsServlet.java
- server/openejb-webservices/src/main/java/org/apache/openejb/server/webservices/saaj/SaajUniverse.java
- tomee/tomee-common/src/main/java/org/apache/tomee/installer/Installer.java
> TOMEE-2319 - fix constant namings

- examples/README.adoc
Signed-off-by: brunobat <brunobat@gmail.com>
> TOMEE-2326 - Define description and rules to create new examples

- examples/arquillian-jpa/pom.xml
- examples/arquillian-jpa/src/test/java/org/superbiz/arquillian/test/persistence/PersistenceTest.java
[TOMEE-2140]: Retire or fix arquillian-jpa example
- Updated POM to remove dependency on outdated arquillian-persistence-dbunit; added dependency on arquillian-universe latest release
> Removed older version of arquillian-persistence-dbunit, added arquillian-universe

- container/openejb-core/src/main/java/org/apache/openejb/assembler/classic/JndiEncBuilder.java
- container/openejb-core/src/main/java/org/apache/openejb/core/cmp/cmp2/EjbSelect.java
- container/openejb-core/src/main/java/org/apache/openejb/core/singleton/SingletonEjbObjectHandler.java
- container/openejb-core/src/main/java/org/apache/openejb/core/timer/EJBCronTrigger.java
- container/openejb-core/src/main/java/org/apache/openejb/math/stat/descriptive/DescriptiveStatistics.java
- container/openejb-core/src/main/java/org/apache/openejb/util/Index.java
- container/openejb-core/src/main/java/org/apache/openejb/util/PojoSerialization.java
- container/openejb-core/src/test/java/org/apache/openejb/config/InjectionTest.java
- container/openejb-core/src/test/java/org/apache/openejb/core/LegacyInterfaceTest.java
- container/openejb-core/src/test/java/org/apache/openejb/core/ivm/naming/IvmContextTest.java
- container/openejb-core/src/test/java/org/apache/openejb/core/webservices/JPACMDIntegrationTest.java
- container/openejb-core/src/test/java/org/apache/openejb/interceptors/StatelessWithAroundInvokeOnlyTest.java
- container/openejb-core/src/test/java/org/apache/openejb/test/entity/cmp2/model/StorageBean.java
- container/openejb-core/src/test/java/org/apache/openejb/util/proxy/SampleLocalBean.java
- container/openejb-jee/src/main/java/org/apache/openejb/jee/BooleanAdapter.java
This PR removes unnecessary boxing and unboxing at the code base within Tomee container.
This PR has the goal to both remove code line and allow a slight performance improvement. Also, provides to the compiler do it when it is indispensable.
> Unnecessary boxing

- examples/mp-metrics-metered/pom.xml
- examples/mp-metrics-metered/src/main/java/org/superbiz/rest/WeatherService.java
- examples/pom.xml
Hi @ivanjunckes I've made this module and ran it with `tomee:run`
I then hit the API with Postman, and here is my finding:
Prometheus format
```
application:daily_status_seconds_count 6.0E-8
application:daily_status_rate_per_second 0.0
application:daily_status_one_min_rate_per_second 1.9999999999999997E-19
application:daily_status_five_min_rate_per_second 1.9999999999999997E-19
application:daily_status_fifteen_min_rate_per_second 1.9999999999999997E-19
```
JSON format
```json
{
"dailyStatus": {
"oneMinuteRate": 2.8216057496353807e-12,
"rate15": {
"alpha": 0.7134952031398099,
"initialized": true,
"interval": 300000000000,
"updates": {},
"value": 2.736166620796627e-13
},
"rate5": {
"alpha": 0.34075936979955623,
"initialized": true,
"interval": 300000000000,
"updates": {},
"value": …
```
> WIP mp-metrics-metered

- .gitignore
- examples/access-timeout-meta/README.adoc
- examples/access-timeout/README.adoc
- examples/github-stylesheet.css
- examples/mp-config-example/README.adoc
Here are two files updated, along with the .gitignore to support Visual Studio Code editing. Let me know if the styling and updates are acceptable, more to come on the examples.
> Updating documentation to Asciidoc

- arquillian/arquillian-tomee-tests/arquillian-tomee-webprofile-tests/src/test/java/org/apache/openejb/arquillian/tests/cmp/CmpServlet.java
- arquillian/arquillian-tomee-tests/arquillian-tomee-webprofile-tests/src/test/java/org/apache/openejb/arquillian/tests/cmp/MyCmpBean.java
- arquillian/arquillian-tomee-tests/arquillian-tomee-webprofile-tests/src/test/java/org/apache/openejb/arquillian/tests/cmp/MyLocalHome.java
- arquillian/arquillian-tomee-tests/arquillian-tomee-webprofile-tests/src/test/java/org/apache/openejb/arquillian/tests/cmp/MyLocalObject.java
- arquillian/arquillian-tomee-tests/arquillian-tomee-webprofile-tests/src/test/java/org/apache/openejb/arquillian/tests/cmp/MyRemoteHome.java
- arquillian/arquillian-tomee-tests/arquillian-tomee-webprofile-tests/src/test/java/org/apache/openejb/arquillian/tests/cmp/MyRemoteObject.java
- container/openejb-core/src/test/java/org/apache/openejb/core/webservices/JPACMDIntegrationTest.java
Adds missing header in the class file
> Adds missing header in the class file

- docs/quickstart.adoc
Category OpenEJB Standalone Server
> Adding category

- examples/moviefun-rest/README.md
I added documentation for only backend code.
> TOMEE-2385 Adding README.md for moviefun-rest example

- owasp-dc-suppression.xml
- pom.xml
Backport of TOMEE-2363, see https://github.com/apache/tomee/pull/276
> [BACKPORT 7.1.x] TOMEE-2363 Introduces OWASP dependency check via profile

- owasp-dc-suppression.xml
- pom.xml
Backport of TOMEE-2363, see #276
> [BACKPORT 7.0.x] TOMEE-2363 Introduces OWASP dependency check via profile

- examples/mp-metrics-metered/README.md
Added README.adoc to mp-metrics-metered/
> TOMEE-2386 Add README.adoc to mp-metrics-metered/

- examples/projectstage-demo/README.adoc
> TOMEE-2392

- server/openejb-cxf-rs/src/test/java/org/apache/openejb/server/cxf/rs/TestCLIFromJaxRSTest.java
Fix for issue 
https://issues.apache.org/jira/browse/TOMEE-2437
> Use correct line separator when checking call result.

- examples/simple-remote-tomcatusers/README.adoc
Added README.adoc for simple-remote-tomcatusers.
> TOMEE-2399 add README.adoc for simple-remote-tomcatusers.

- pom.xml
- server/openejb-client/pom.xml
- server/openejb-ssh/pom.xml
- server/openejb-ssh/src/main/java/org/apache/openejb/server/ssh/OpenEJBCommands.java
- server/openejb-ssh/src/main/java/org/apache/openejb/server/ssh/OpenEJBJaasPasswordAuthenticator.java
- server/openejb-ssh/src/main/java/org/apache/openejb/server/ssh/OpenEJBShellFactory.java
- server/openejb-ssh/src/main/java/org/apache/openejb/server/ssh/SSHServer.java
- server/openejb-ssh/src/test/java/org/apache/openejb/server/ssh/SSHServerTest.java
- tomee/tomee-embedded/pom.xml
- Upgraded to latest 2.1.0 sshd
> Fixes issue https://issues.apache.org/jira/browse/TOMEE-1287

- itests/failover/src/test/java/org/apache/openejb/itest/failover/RandomConnectionStrategyTest.java
- itests/legacy-client/src/test/java/org/apache/openejb/itest/legacy/LegacyClientTest.java
- itests/legacy-server/src/test/java/org/apache/openejb/itest/legacy/LegacyServerTest.java
Fix for issue https://issues.apache.org/jira/projects/TOMEE/issues/TOMEE-2446
> Fix for issue TOMEE-2446

- tomee/pom.xml
- tomee/tomee-catalina/pom.xml
- tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/TomcatWebAppBuilder.java
- tomee/tomee-config/pom.xml
- tomee/tomee-config/src/main/java/org/apache/tomee/config/TomEESystemConfig.java
Initial attempt for TomEE system config.
> (TOMEE-2438) Centralise TomEE and OpenEJB system properties

- tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/routing/SimpleRouter.java
- tomee/tomee-juli/src/main/java/org/apache/tomee/jul/handler/rotating/LocalFileHandler.java
- tomee/tomee-loader/src/main/java/org/apache/tomee/loader/TomcatEmbedder.java
Fixed a few issues related to closing of resources uncovered from SonarQube
Signed-off-by: Martin Toshev <marto8808@gmail.com>
> Fixed a few issues related to closing of resources

- examples/applicationcomposer-jaxws-cdi/README.adoc
- examples/applicationcomposer-jaxws-cdi/src/test/java/org/superbiz/example/jaxws/MeetingPlannerTest.java
Jira ticket: https://issues.apache.org/jira/browse/TOMEE-2370 .
> Add README.adoc to applicationcomposer-jaxws-cdi/ - TOMEE-2370

- pom.xml
https://issues.apache.org/jira/browse/TOMEE-2463
> TOMEE-2463 - MyFaces 2.3.3

- examples/rest-applicationcomposer-mockito/README.adoc
Jira issue: https://issues.apache.org/jira/browse/TOMEE-2393.
> Added README.adoc: TOMEE-2393

- examples/cdi-realm/README.adoc
Jira issue: https://issues.apache.org/jira/browse/TOMEE-2372.
> Added README.adoc to cdi-realm - TOMEE-2372

- examples/webservice-ws-with-resources-config/README.adoc
Jira task https://issues.apache.org/jira/browse/TOMEE-2402
> Added ReadMe file

- examples/concurrency-utils/README.adoc
Jira task: https://issues.apache.org/jira/browse/TOMEE-2375.
> Add README.adoc to concurrency-utils example: TOMEE-2375

- docs/tomee-directory-structure.adoc
- Added title for tomee-directory-structure.html file
- Decreased font size for TomEE Directory Layout
- Changing *$tomee-install-dir>* to be in strong text format
> tomee-directory-structure.html formatting additions

- arquillian/arquillian-tomee-remote/src/main/java/org/apache/tomee/arquillian/remote/RemoteTomEEConfiguration.java
The default is webprofile, and ignore should be consistent.
> Added ignore qualifier to the getter of the classifier.

- container/openejb-core/src/main/java/org/apache/openejb/assembler/classic/DelegatePermissionCollection.java
- If it is list if same permission is added multiple times that list will grow.
> Keep permissions in Set.

- examples/jpa-hibernate/README_pt.adoc
Hey guys, so this is my first (of many) commit in the project. I worked in the translate for the portuguese but during the work I felt the need to improve it in the intention of helping more beginner people (like me).
I am open for suggestions. Thanks.
> TOMEE-2474 Translate to Portuguese: examples/jpa-hibernate.

- examples/jaxrs-filter/README.adoc
- examples/jaxrs-filter/pom.xml
- examples/jaxrs-filter/src/main/java/org/superbiz/filterexample/ExampleServlet.java
- examples/jaxrs-filter/src/main/java/org/superbiz/filterexample/InboundFilter.java
- examples/jaxrs-filter/src/main/webapp/WEB-INF/web.xml
- examples/jaxrs-filter/src/main/webapp/index.jsp
- examples/jaxrs-filter/src/main/webapp/unauthorized/index.jsp
https://issues.apache.org/jira/browse/TOMEE-2485
This is a really simple example, but it presents a way to handle requests early on in the servlet lifecycle, and confirms yet another feature available through the TomEE container.
I think this is decent for an example, but I'd appreciate any advice relating to state-management, the servlet lifecycle, etc.
> JAX-RS filter example (JIRA 2482)

- examples/tomee-jersey-eclipselink/README.adoc
- examples/tomee-jersey-eclipselink/pom.xml
- examples/tomee-jersey-eclipselink/src/test/java/org/superbiz/service/JerseyApplicationTest.java
- examples/tomee-jersey-eclipselink/src/test/resources/META-INF/persistence.xml
- examples/tomee-jersey-eclipselink/src/test/resources/arquillian.xml
Jira issue: https://issues.apache.org/jira/browse/TOMEE-2401
> Add README.adoc: Tomee 2401

- examples/mp-config-example/README_pt.adoc
Signed-off-by: rhuanrocha <rhuan080@gmail.com>
> TOMEE-2486 | Translate to Portuguese: examples/mp-config-example

- examples/deltaspike-i18n/README.adoc
Add README.adoc to deltaspike-i18n/
> TOMEE-2381 Add README.adoc to deltaspike-i18n/

- examples/mvc-cxf-hibernate/README_pt.adoc
ticket of Jira = https://issues.apache.org/jira/browse/TOMEE-2491
> TOMEE-2491 - add translate in PT to mvc-cxf-hibernate

- examples/simple-remote-tomcatusers/README_pt.adoc
- examples/testing-security-2/README.adoc
- examples/testing-security-3/README.adoc
- examples/testing-security-4/README.adoc
- examples/testing-security/README.adoc
- examples/testing-security/README_pt.adoc
I am newbie in translation contribution. But I created one Jira issue TomEE-2494 and I will resolve with that PR. I put some comments below.
> Tomee 2494 - Add translation to PT-BR to security-examples directory

- docs/activemqresourceadapter-config.adoc
Changed the page so that the table renders correctly.
> ActiveMQ Resource Adapter Config Page.  Fixes issue TOMEE-2527

- examples/jpa-enumerated/README_pt.adoc
Translation to portuguese jpa-enumerated example
> TOMEE - 2524 Translate to portuguese: examples/jpa-enumerated

- examples/simple-rest/README_pt.adoc
Hey guys, so I did a little improvement at the english version and I translated to Portuguese.
If you need anything, I'm at your disposal.
Thanks.
> TOMEE-2480 Translate to Portuguese: examples/simple-rest.

- container/openejb-core/src/main/java/org/apache/openejb/assembler/classic/DelegatePermissionCollection.java
- container/openejb-core/src/main/java/org/apache/openejb/core/entity/EntityContainer.java
- container/openejb-core/src/main/java/org/apache/openejb/core/entity/EntityEjbHomeHandler.java
- container/openejb-core/src/main/java/org/apache/openejb/util/ArrayEnumeration.java
- container/openejb-core/src/main/java/org/apache/openejb/web/LightweightWebAppBuilder.java
- container/openejb-core/src/test/java/org/apache/openejb/core/security/SecurityServiceImplTest.java
- server/openejb-http/src/main/java/org/apache/openejb/server/httpd/HttpRequestImpl.java
Also cleanup code in HttpRequestImpl.
> Make ArrayEnumeration generics aware

- container/openejb-core/src/main/java/org/apache/openejb/assembler/classic/Assembler.java
Check https://issues.apache.org/jira/projects/TOMEE/issues/TOMEE-2499
> Deprecate unused method (tomee-2499)

- docs/tomee-embedded-maven-plugin.adoc
Reformatted and added correct maven group id
> Updated TomEE Embedded Maven Plugin page. Fixes TOMEE-2484

- examples/mp-rest-client/src/test/java/org/superbiz/rest/BookResourceTest.java
> Cleanup test code.

- docs/java-compatibility.adoc
This is a live document until TomEE 8.0.0 is released. Till that point of time, any updates (either additions/removal) of Java versions support can be done to this document
> Create java-compatibility.adoc [TOMEE-2540]

- itests/tomee-server-composer/src/main/java/org/apache/tomee/server/composer/TomEE.java
> Code to add support for TOMEE-2542

- examples/xa-datasource/.gitignore
- examples/xa-datasource/README.md
- examples/xa-datasource/grinder.sh
- examples/xa-datasource/pom.xml
- examples/xa-datasource/src/assembly/tests.xml
- examples/xa-datasource/src/main/java/org/superbiz/injection/jpa/Movie.java
- examples/xa-datasource/src/main/java/org/superbiz/injection/jpa/Movies.java
- examples/xa-datasource/src/main/java/org/superbiz/injection/jpa/MoviesDirect.java
- examples/xa-datasource/src/main/java/org/superbiz/injection/jpa/MoviesXA.java
- examples/xa-datasource/src/main/java/org/superbiz/rest/MovieService.java
- examples/xa-datasource/src/main/resources/META-INF/persistence.xml
- examples/xa-datasource/src/main/webapp/WEB-INF/resources.xml
Add performance test to xa-datasource example
> Backport of #488 from master

- examples/alternate-descriptors/README_pt.adoc
Link to Jira : https://issues.apache.org/jira/browse/TOMEE-2545
> TOMEE-2545 - Translate to Portuguese alternate-descriptors

- examples/access-timeout-meta/README_pt.adoc
Jira : https://issues.apache.org/jira/browse/TOMEE-2544
> TOMEE-2544- Translate to Portuguese example-access-timeout-meta.

- examples/cdi-events/README_pt.adoc
link to jira : https://issues.apache.org/jira/browse/TOMEE-2543
> TOMEE-2543 - Translate to Portuguese: examples/cdi-events .

- examples/application-composer/README_pt.adoc
This PR contains translate to portuguese and fix the title in the doc in english .
Link Jira : https://issues.apache.org/jira/browse/TOMEE-2550
> TOMEE-2550-Translate to portuguese: examples/application-composer

- examples/deltaspike-i18n/README_pt.adoc
Link to Jira : https://issues.apache.org/jira/browse/TOMEE-2554
> TOMEE-2554-Translate to portuguese of deltaspike-i18n

- examples/mp-faulttolerance-fallback/README_pt.adoc
Link to Jira : https://issues.apache.org/jira/browse/TOMEE-2553
> TOMEE-2553 - Translate to portuguese-mp-faulttolerance-fallback

- examples/cdi-alternative-and-stereotypes/README_pt.adoc
This PR contains translate to portuguese and small fix in the doc in english .
Link Jira : https://issues.apache.org/jira/browse/TOMEE-2551
> TOMEE-2551 - Translate to portuguese-cdi-alternative-and-stereotypes

- tomee/tomee-loader/src/main/java/org/apache/tomee/loader/TomEEJarScanner.java
See ticket https://issues.apache.org/jira/browse/TOMEE-2564 for all details of the issue
> TOMEE-2564 Classpath with :: on Linux is cause an infinite loop on War deploy

- examples/applicationexception/README_pt.adoc
Link to Jira -> https://issues.apache.org/jira/browse/TOMEE-2556
> TOMEE-2556-Translate to portuguese to applicationexception example

- examples/async-methods/README_pt.adoc
Link to Jira : https://issues.apache.org/jira/browse/TOMEE-2560
> TOMEE-2560-Translate to Portuguese the async-methods example.

- examples/async-postconstruct/README_pt.adoc
Link to Jira : https://issues.apache.org/jira/browse/TOMEE-2562
- contains translate to portuguese and an small fix in english .
> TOMEE-2562- Translate to Portuguese example-async-postconstruct.

- examples/bean-validation-design-by-contract/README_pt.adoc
Link to Jira : https://issues.apache.org/jira/browse/TOMEE-2563
> TOMEE-2563- Translate to portuguese-bean-validation-design-by-contract

- examples/cdi-application-scope/README_pt.adoc
Hey guys there is my translation of cdi-application-scope example.
Thank you ;)
jira task: https://issues.apache.org/jira/browse/TOMEE-2568
> TOMEE-2568 - translation of cdi-application-scope example.

- examples/cdi-interceptors/README_pt.adoc
Hey guys there is my translation of cdi-application-scope example.
Thank you ;)
jira task: https://issues.apache.org/jira/browse/TOMEE-2569
> TOMEE-2569 - translation of cdi-interceptor example.

- examples/cdi-produces-disposes/README_pt.adoc
Link to Jira : https://issues.apache.org/jira/browse/TOMEE-2571
> TOMEE-2571- translate example cdi-produces-disposes.

- examples/cdi-produces-field/README_pt.adoc
Hey guys there is my translation of cdi-produces-field example.
Thank you ;)
jira task: https://issues.apache.org/jira/browse/TOMEE-2572
> TOMEE-2572 - translation of cdi-produces-field

- examples/cdi-realm/README.adoc
- examples/cdi-realm/README_pt.adoc
Hey guys there is my translation of cdi-realm example.
Thank you ;)
jira task: https://issues.apache.org/jira/browse/TOMEE-2574
> TOMEE-2574 - translation of cdi-realm

- examples/cdi-request-scope/README_pt.adoc
Hey guys there is my translation of cdi-request-scope.
Thank you ;)
jira task: https://issues.apache.org/jira/browse/TOMEE-2575
> TOMEE-2575 - translate of examples/cdi-request-scope

- README.adoc
I saw this two simple mistakes and corrected them.
Jira task: https://issues.apache.org/jira/browse/TOMEE-2576
> TOMEE-2576 - correcting two simple word mistakes.

- examples/cdi-qualifier/README_pt.adoc
Link to Jira : https://issues.apache.org/jira/browse/TOMEE-2573
> TOMEE-2573-Translate to portuguese-examples-cdi-qualifier

- examples/cloud-tomee-azure/README.adoc
- examples/cloud-tomee-azure/README_pt.adoc
Link to Jira : https://issues.apache.org/jira/browse/TOMEE-2577
> TOMEE-2577 - Translate to portuguese cloud-tomee-azure example 

- examples/cdi-session-scope/README.adoc
- examples/cdi-session-scope/README_pt.adoc
Hey guys there is my translation of cdi-session-scope and some fixes in English version.
Thank you ;)
jira task: https://issues.apache.org/jira/browse/TOMEE-2578
> TOMEE-2578 - Translation of the examples/cdi-session-scope to Portuguese.

- examples/change-jaxws-url/README.adoc
- examples/change-jaxws-url/README_pt.adoc
Hey guys there is my translation of change-jaxws-url and some fixes in English version.
Thank you ;)
jira task: https://issues.apache.org/jira/browse/TOMEE-2579
> TOMEE-2579 - Translation of the examples/change-jaxws-url to Portuguese.

- container/openejb-core/src/main/java/org/apache/openejb/resource/AutoConnectionTracker.java
- container/openejb-core/src/main/java/org/apache/openejb/resource/activemq/jms2/JMS2.java
- container/openejb-core/src/main/java/org/apache/openejb/resource/activemq/jms2/JMSContextImpl.java
- container/openejb-core/src/main/java/org/apache/openejb/resource/activemq/jms2/JMSProducerImpl.java
- container/openejb-core/src/main/java/org/apache/openejb/resource/activemq/jms2/TomEEConnectionFactory.java
- container/openejb-core/src/main/java/org/apache/openejb/resource/activemq/jms2/TomEEManagedConnection.java
- container/openejb-core/src/main/java/org/apache/openejb/resource/activemq/jms2/TomEEManagedConnectionFactory.java
- container/openejb-core/src/main/java/org/apache/openejb/resource/activemq/jms2/TomEEManagedConnectionProxy.java
- container/openejb-core/src/main/java/org/apache/openejb/resource/activemq/jms2/TomEERAConnectionFactory.java
- container/openejb-core/src/main/java/org/apache/openejb/resource/activemq/jms2/cdi/JMS2CDIExtension.java
* Fix TOMEE-2229: JMSContext Injected by TomEE does not participate in JTA
* Fix TOMEE-2650: TomEE Creating non-JTA Sessions
* Fix TOMEE-2651: TomEE doesn't return JMS Connection to pool after a Transaction Timeout
* Fix TOMEE-2652: TransactionSupport parameter not honored on JMS Connection Factory resources
> Fix several JMS/JMS2.0 bugs [tomee-7.0.x]

- examples/spring-data-proxy-meta/README.adoc
- examples/spring-data-proxy-meta/README_pt.adoc
link to jira = https://issues.apache.org/jira/browse/TOMEE-2608
> TOMEE-2608-translate example Spring-data-proxy-meta

- examples/webservice-ssl-client-cert/README_pt.adoc
link to Jira  = https://issues.apache.org/jira/browse/TOMEE-2615
> TOMEE-2615-translate example web services ssl .

- examples/cdi-application-scope/README_es.adoc
Add documentation in language spanish
> CDI-DOCUMENTATION-SPANISH

- examples/websocket-tls-basic-auth/README.adoc
- examples/websocket-tls-basic-auth/README_pt.adoc
Link to Jira  = https://issues.apache.org/jira/browse/TOMEE-2613
> TOMEE-2613-Translate to Portuguese: examples/websocket-tls-basic-auth

- examples/simple-cdi-interceptor/README.adoc
- examples/simple-cdi-interceptor/README_pt.adoc
Hey guys there is my translation of simple-cdi-interceptor and some fixes in English version.
Thank you ;)
jira task: https://issues.apache.org/jira/browse/TOMEE-2580
> TOMEE-2580 - Translation of the examples/simple-cdi-interceptor to Portuguese.

- examples/datasource-versioning/README_pt.adoc
ticket of Jira = https://issues.apache.org/jira/browse/TOMEE-2583
> TOMEE-2583 - add translate in PT to examples/datasource-versioning

- examples/tomee-jms-portability/README_pt.adoc
ticket of Jira = https://issues.apache.org/jira/browse/TOMEE-2602
> TOMEE-2602 - add translate in PT to examples/tomee-jms-portability

- examples/spring-data-proxy/README.adoc
- examples/spring-data-proxy/README_pt.adoc
Link to jira  = https://issues.apache.org/jira/browse/TOMEE-2607
> TOMEE-2607-translate to pt Spring-data-proxy

- examples/deltaspike-fullstack/README_pt.adoc
link to jira  = https://issues.apache.org/jira/browse/TOMEE-2609
> TOMEE-2609-translate to portuguese the example deltaspike-fullstack.

- examples/mp-custom-healthcheck/README_es.adoc
https://issues.apache.org/jira/browse/TOMEE-2671
> [TOMEE-2671] Adding mp-custom-healthcheck Spanish Translation

- examples/async-methods/README_es.adoc
- examples/async-methods/README_pt.adoc
https://issues.apache.org/jira/browse/TOMEE-2669
> [TOMEE-2669] [DOC] [Translation] Translate async-methods example to Spanish

- examples/groovy-jpa/README.adoc
- examples/groovy-jpa/README_es.adoc
Add documentation of example groovy jpa.
> TOMEE-2383

- examples/mp-metrics-timed/README_es.adoc
https://issues.apache.org/jira/browse/TOMEE-2682
> [TOMEE-2682] Translate MicroProfile Metrics Timed Example to Spanish

- examples/mp-metrics-counted/README_es.adoc
- examples/mp-metrics-gauge/README_es.adoc
https://issues.apache.org/jira/browse/TOMEE-2679
> [TOMEE-2679] Translate MicroProfile Metrics Counted Example to Spanish

- examples/mp-metrics-histogram/README_es.adoc
https://issues.apache.org/jira/browse/TOMEE-2680
> [TOMEE-2680] Translate MicroProfile Metrics Histogram Example to Spanish

- examples/mp-metrics-metered/README_es.adoc
https://issues.apache.org/jira/browse/TOMEE-2681
> [TOMEE-2681] Translate MicroProfile Metrics Metered Example to Spanish

- examples/simple-rest/README_es.adoc
Link to Jira: https://issues.apache.org/jira/browse/TOMEE-2698
> TOMEE-2698: Translate to spanish simple-rest

- examples/datasource-ciphered-password/README_pt.adoc
link to jira : https://issues.apache.org/jira/browse/TOMEE-2707
> TOMEE-2707-Translate example datasource-ciphered-password

- examples/cucumber-jvm/README_pt.adoc
Link to Jira : https://issues.apache.org/jira/browse/TOMEE-2700
> TOMEE-2700-Translate to portuguese - Cucumber-jvm

- examples/mp-faulttolerance-timeout/README_pt.adoc
Link to Jira : https://issues.apache.org/jira/browse/TOMEE-2699
> TOMEE-2699-Translate to portuguese MicroProfile - Timeout 

- examples/async-servlet/README.adoc
- examples/async-servlet/README_pt.adoc
Link to Jira: https://issues.apache.org/jira/browse/TOMEE-2697
> TOMEE-2697-Translate to portuguese-async-servlet

- examples/mp-jwt-bean-validation/README_es.adoc
Adding Spanish Translation for example: MicroProfile JWT with Bean Validation
> [TOMEE-2714] Spanish Translation mp-jwt-bean-validation

- examples/myfaces-codi-demo/README.adoc
- examples/myfaces-codi-demo/README_es.adoc
https://issues.apache.org/jira/browse/TOMEE-2723
> [TOMEE-2723] Fix myfaces-codi-demo Example and Add Spanish Translation

- maven/tomee-maven-plugin/src/main/java/org/apache/openejb/maven/plugin/AbstractTomEEMojo.java
This PR provides a fix for https://issues.apache.org/jira/projects/TOMEE/issues/TOMEE-2736 by using the property override mechanism of RemoteServer.
It fixes a regression introduced with https://github.com/apache/tomee/commit/6d5e5a39006492fcd6d1ee5b80cbe460168dba86 , in which SystemProperties are cached within a static context in `RemoteServer`.
This is a problem in environments, where a shared JVM is used for the TomEE container, e.g. for integration testing in build tools such as Maven, where the (Maven) JVM is used and shared across different module builds.
However, this is not a problem for production / standalone TomEE.
> TOMEE-2736 - Override cached system properties in RemoteServer for Maven TomEE Plugin

- examples/dynamic-datasource-routing/README_pt.adoc
Link to Jira  :  https://issues.apache.org/jira/browse/TOMEE-2720
> TOMEE-2720-Translate dynamic-datasource-routing

- examples/dynamic-dao-implementation/README_pt.adoc
Link to Jira : https://issues.apache.org/jira/browse/TOMEE-2708
> TOMEE-2708-translate to portuguese dynamic-dao.

- container/openejb-core/pom.xml
- tomee/tomee-plume-webapp/pom.xml
- tomee/tomee-plus-webapp/pom.xml
Worked with Jon to get this to an acceptable way to fix the micro profile.
> Added missing dependency for microprofile

- pom.xml
> Update tomcat dependency to 9.0.29

- pom.xml
Link to Jira   : https://issues.apache.org/jira/browse/TOMEE-2734
> TOMEE-2734-Upgrade CXF to 3.3.4

- examples/mvc-cxf-hibernate/pom.xml
- examples/mvc-cxf/pom.xml
- examples/mvc-resteasy/pom.xml
Link to Jira = https://issues.apache.org/jira/browse/TOMEE-2759
> TOMEE-2759-Update-Eclipse-Krazo

- examples/deltaspike-configproperty/pom.xml
- examples/deltaspike-exception-handling/pom.xml
- examples/deltaspike-fullstack/pom.xml
- examples/deltaspike-i18n/pom.xml
- examples/mvc-cxf-hibernate/pom.xml
- examples/mvc-cxf/pom.xml
Link to Jira : https://issues.apache.org/jira/browse/TOMEE-2755
> TOMEE-2755-Update-Apache-Deltaspike

- examples/groovy-jpa/README_pt.adoc
Link to jira : https://issues.apache.org/jira/browse/TOMEE-2815
> TOMEE-2815 -Translate to Portuguese: examples/groovy-jpa

- examples/ear-testing/README_pt.adoc
Translate to portuguese of  examples/ear-testing
Link to Jira : https://issues.apache.org/jira/browse/TOMEE-2814
> TOMEE-2814 -Translate to Portuguese: examples/ear-testing

- examples/injection-of-env-entry/README.adoc
- examples/injection-of-env-entry/README_pt.adoc
Link to Jira : https://issues.apache.org/jira/browse/TOMEE-2819
> TOMEE-2819 Translate to Portuguese: examples/injection-of-env-entry

- examples/jaxrs-filter/README_pt.adoc
link to jira: https://issues.apache.org/jira/browse/TOMEE-2820
> TOMEE-2820-Translate to Portuguese: examples/jaxrs-filter

- examples/dynamic-proxy-to-access-mbean/README_pt.adoc
Translate to portuguese of example/dynamic-proxy-to-access-mbean
link jira: https://issues.apache.org/jira/browse/TOMEE-2813
> TOMEE-2813 - Translate to Portuguese: examples/dynamic-proxy-to-access-mbean	

- examples/injection-of-ejbs/README_pt.adoc
Link to Jira: https://issues.apache.org/jira/browse/TOMEE-2817
> TOMEE-2817-Translate to Portuguese: examples/injection-of-ejbs

- examples/injection-of-entitymanager/README_pt.adoc
Link to Jira: https://issues.apache.org/jira/browse/TOMEE-2818
> TOMEE-2818-Translate to Portuguese: examples/injection-of-entitymanager

- examples/jsonb-configuration/README.adoc
- examples/jsonb-configuration/README_pt.adoc
Link to Jira : https://issues.apache.org/jira/browse/TOMEE-2822
> TOMEE-2822-Translate to Portuguese: examples/jsonb-configuration

- examples/moviefun-rest/README_pt.adoc
link to Jira:https://issues.apache.org/jira/browse/TOMEE-2828
> Translate to Portuguese: examples/MovieFun REST

- examples/mp-config-source-database/README_es.adoc
- examples/mp-config-source-database/README_pt.adoc
Link to Jira:https://issues.apache.org/jira/browse/TOMEE-2829
> Translate to Portuguese: examples/mp-config-source-database

- examples/mp-jsonb-configuration/README_pt.adoc
Link to Jira: https://issues.apache.org/jira/browse/TOMEE-2830
> Translate to Portuguese: examples/mp-jsonb-configuration

- examples/mp-jwt-bean-validation/README_pt.adoc
link to jira: https://issues.apache.org/jira/browse/TOMEE-2831
> Translate to Portuguese: examples/mp-jwt-bean-validation

- examples/arquillian-jpa/README_es.adoc
Spanish translation README.adoc file examples/ arquillian-jpa
> TOMME<2834> translate to spanish: examples/arquillian-jpa README_es.adoc

- examples/jpa-hibernate/README_es.adoc
The README file is translated into Spanish,adding file README_es.adoc
> adding file README_es.adoc

- examples/mp-metrics-histogram/README_es.adoc
- examples/mp-metrics-histogram/README_pt.adoc
add output test in doc es and en
link to jira: https://issues.apache.org/jira/browse/TOMEE-2836
> TOMEE-2836 Translate to Portuguese: examples/mp-metrics-histogram

- examples/mp-metrics-gauge/README_pt.adoc
Link to Jira: https://issues.apache.org/jira/browse/TOMEE-2833
> Translate to Portuguese: examples/mp-metrics-gauge

- docs/tomee-mp-getting-started.adoc
- maven/tomee-webapp-archetype/src/main/resources/archetype-resources/pom.xml
Link to Jira: https://issues.apache.org/jira/browse/TOMEE-2483
- update doc
- align tag
> TOMEE-2483 Update for TomEE Maven Plugin documentation

- examples/xa-datasource/README.adoc
- examples/xa-datasource/README_pt.adoc
Please validate the translation.
> Portuguese translation README.adoc file examples/xa-datasource

- container/openejb-core/src/main/java/org/apache/openejb/cdi/transactional/InterceptorBase.java
Adjust message of the exception when use UserTransaction from @Transactional call 
link to jira : https://issues.apache.org/jira/browse/TOMEE-1563
credit to Daniel Soro .
> TOMEE-1563 Adjust message of the exception 

- examples/mp-metrics-counted/Dockerfile
- examples/mp-metrics-counted/README_pt.adoc
- translate and update version Tomee in Dockerfile
link to jira:https://issues.apache.org/jira/browse/TOMEE-2832
> Translate to Portuguese: examples/mp-metrics-counted

- examples/webservice-ws-with-resources-config/README_pt.adoc
Create the file README_pt.adoc for the portuguese translation.
> Portuguese translation README.adoc file examples/webservice-ws-with-resources-config

- examples/mbean-auto-registration/README_pt.adoc
link to Jira: https://issues.apache.org/jira/browse/TOMEE-2827
> Translate to Portuguese: examples/mbean-auto-registration

- container/openejb-core/src/main/java/org/apache/openejb/cdi/ThreadSingletonServiceImpl.java
- pom.xml
> Revert "TOMEE-2809 Update OWB to 2.0.16"

- examples/mp-metrics-metered/README_pt.adoc
link to jira: https://issues.apache.org/jira/browse/TOMEE-2869
> TOMEE:2869 Translate to Portuguese: examples/mp-metrics-metered

- examples/mp-rest-jwt-jwk/README_pt.adoc
Link to Jira: https://issues.apache.org/jira/browse/TOMEE-2873
> TOMEE-2873 Translate to Portuguese: examples/mp-rest-jwt-jwk

- container/openejb-core/src/main/java/org/apache/openejb/assembler/classic/Assembler.java
Moved the if null check for appContext before appContext is used so any potential NPE's will be caught.
> Removed potential NPE.  Fixes TOMEE-1399

- examples/mp-rest-jwt-principal/README_pt.adoc
Link to JIra : https://issues.apache.org/jira/browse/TOMEE-2875
> TOMEE-2875 Translate to Portuguese: examples/mp-rest-jwt-principal

- examples/mp-rest-client/README.adoc
- examples/mp-rest-client/README_es.adoc
- examples/mp-rest-client/README_pt.adoc
link to jira: https://issues.apache.org/jira/browse/TOMEE-2871
> TOMEE-2871 - Translate to Portuguese: examples/mp-rest-client

- examples/mp-metrics-timed/README_pt.adoc
link to jira : https://issues.apache.org/jira/browse/TOMEE-2870
> TOMEE-2870 Translate to Portuguese: examples/mp-metrics-timed

- examples/mp-rest-jwt/README_pt.adoc
link to jira: https://issues.apache.org/jira/browse/TOMEE-2872
> TOMEE-2872 Translate to Portuguese: examples/mp-rest-jwt

- examples/persistence-fragment/README_pt.adoc
link to jira : https://issues.apache.org/jira/browse/TOMEE-2881
> TOMEE-2881 Translate to Portuguese: examples/persistence-fragment

- examples/myfaces-codi-demo/README.adoc
- examples/myfaces-codi-demo/README_es.adoc
- examples/myfaces-codi-demo/README_pt.adoc
Link to Jira: https://issues.apache.org/jira/browse/TOMEE-2880
> TOMEE-2880 Translate to Portuguese: examples/myfaces-codi-demo

- examples/mp-rest-jwt-public-key/README.adoc
- examples/mp-rest-jwt-public-key/README_pt.adoc
Link to Jira: https://issues.apache.org/jira/browse/TOMEE-2877
> TOMEE-2877 Translate to Portuguese: examples/mp-rest-jwt-public-key

- examples/pojo-webservice/README_pt.adoc
Link to Jira: https://issues.apache.org/jira/browse/TOMEE-2882
> TOMEE-2882 Translate to Portuguese: examples/pojo-webservice

- examples/projectstage-demo/README_pt.adoc
Linkt to Jira: https://issues.apache.org/jira/browse/TOMEE-2883
> TOMEE-2883 Translate to Portuguese:examples/projectstage-demo

- examples/realm-in-tomee/README_pt.adoc
link to jira : https://issues.apache.org/jira/browse/TOMEE-2889
> TOMEE-2889 Translate to Portuguese: examples/realm-in-tomee

- examples/quartz-app/README_pt.adoc
link to jira : https://issues.apache.org/jira/browse/TOMEE-2888
> TOMEE-2888 Translate to Portuguese: examples/quartz-app

- examples/resources-jmx-example/README_pt.adoc
Link to Jira: https://issues.apache.org/jira/browse/TOMEE-2891
> TOMEE-2891 Translate to Portuguese: examples/resources-jmx-example

- examples/singleton-startup-ordering/README_pt.adoc
Link to Jira : https://issues.apache.org/jira/browse/TOMEE-2897
> TOMEE-2897 - Translate to Portuguese: examples/singleton-startup-ordering/

- examples/tomee-jersey-eclipselink/README_pt.adoc
Translate document Readme example
> TOMEE-2896 Translate to Portuguese: examples/tomee-jersey-eclipselink

- examples/injection-of-ejbs/README_es.adoc
- examples/injection-of-ejbs/README_pt.adoc
- Updated EJB annotation syntax on files
- Removed non-required comments on code
- Removed `recently` from Java EE 5 context
> TOMEE-2899 Add Spanish Translation: injection-of-ejbs & adjustments

- examples/jaxrs-json-provider-jettison/README_es.adoc
Link to Jira: https://issues.apache.org/jira/browse/TOMEE-2900
> Translate to Spanish the document examples/jax-rs-json-provider-jettison

- examples/rest-xml-json/README.adoc
- examples/rest-xml-json/README_pt.adoc
Link to Jira : https://issues.apache.org/jira/browse/TOMEE-2895
> TOMEE-2895 Translate to Portuguese: examples/rest-xml-json

- examples/polling-parent/README_pt.adoc
This PR to refer the issue https://issues.apache.org/jira/browse/TOMEE-2901
> Portuguese translation README.adoc file examples/polling-parent

- examples/schedule-events/README_pt.adoc
description: Link to Jira : https://issues.apache.org/jira/browse/TOMEE-2914
> Portuguese translation README.adoc file examples/schedule-events

- pom.xml
https://issues.apache.org/jira/browse/TOMEE-2947
> TOMEE-2947 - Upgrades to Quartz Scheduler OpenEJB Shade 2.2.4

- container/openejb-core/src/main/java/org/apache/openejb/core/timer/EjbTimerServiceImpl.java
- container/openejb-core/src/main/java/org/apache/openejb/resource/quartz/QuartzResourceAdapter.java
- pom.xml
https://issues.apache.org/jira/browse/TOMEE-2947
Should fix the compile issues, @jeanouii  (sorry) - did a quick build without compilation failures.
Aligns with the changes conducted for 7.0.x and 7.1.x by @jgallimore 
- https://github.com/apache/tomee/commit/cb30ecb1391cc14e4bb0108a22e2ec7e9775303f
- https://github.com/apache/tomee/commit/8899dd7e1a1dd012547365f69ee9aff982086cfb
> TOMEE-2947 - Upgrades to Quart Scheduler OpenEJB Shade 2.2.4

- examples/rest-cdi/README.adoc
- examples/rest-cdi/README_pt.adoc
Link to Jira : https://issues.apache.org/jira/browse/TOMEE-2894
> TOMEE-2894 Translate to Portuguese: examples/rest-cdi

- container/openejb-core/src/main/java/org/apache/openejb/core/timer/CalendarTimerData.java
- container/openejb-core/src/main/java/org/apache/openejb/core/timer/EJBCronTrigger.java
- container/openejb-core/src/main/java/org/apache/openejb/core/timer/EjbTimerServiceImpl.java
- container/openejb-core/src/main/java/org/apache/openejb/core/timer/TimerData.java
- container/openejb-core/src/main/java/org/apache/openejb/core/timer/TimerExpiredException.java
- container/openejb-core/src/test/java/org/apache/openejb/timer/EJBCronTriggerTest.java
- container/openejb-core/src/test/java/org/apache/openejb/timer/InitialIntervalTimerTest.java
But puts the Timer into a state where it won't trigger
> TOMEE-2937 Make sure endDate in the past does not fail

- pom.xml
- Fixes OWASP execution on Jenkins CI (backport from https://github.com/apache/tomee/pull/750)
- Updates OWASP plugin to 6.0.5 (was 4.0.0)
```
mvn -U --show-version --fail-at-end clean install -Pmain,owasp-check -DskipTests
```
```
mvn -U --show-version --fail-at-end clean install -Pmain,owasp-report -DskipTests
```
> [7.0.x] TOMEE-2957: Fixes OWASP configuration on Jenkins

- pom.xml
- Fixes OWASP execution on Jenkins CI (backport from https://github.com/apache/tomee/pull/750)
- Updates OWASP plugin to 6.0.5 (was 4.0.0)
```
mvn -U --show-version --fail-at-end clean install -Pmain,owasp-check -DskipTests
```
```
mvn -U --show-version --fail-at-end clean install -Pmain,owasp-report -DskipTests
```
> [7.1.x] TOMEE-2957: Fixes OWASP configuration on Jenkins

- examples/xa-datasource/README_es.adoc
link to jira : https://issues.apache.org/jira/browse/TOMEE-2967
> Spanish translation README.adoc file examples/xa-datasource

- pom.xml
https://issues.apache.org/jira/browse/TOMEE-2969
> TOMEE-2969 - Upgrade MyFaces to 2.3.8

- examples/serverless-tomee-plus/README_pt.adoc
Translate to Portuguese the example serverless-tomee-plus
link to Jira: https://issues.apache.org/jira/browse/TOMEE-2963
> TOMEE-2963 Translate to Portuguese: examples/serverless-tomee-plus

- examples/serverless-tomee-plume/README_pt.adoc
Translate to Portuguese the example serverless-tomee-plume
link to Jira: https://issues.apache.org/jira/browse/TOMEE-2962
> TOMEE-2962 Translate to Portuguese: serverless-tomee-plume

- examples/serverless-tomee-microprofile/README_pt.adoc
Translate to Portuguese the example serverless-tomee-microprofile
link to Jira: https://issues.apache.org/jira/browse/TOMEE-2927
> TOMEE-2927 Translate to Portuguese: examples/serverless-tomee-mp

- examples/serverless-builder/README_pt.adoc
link to jira : https://issues.apache.org/jira/browse/TOMEE-2926
> TOMEE-2926: Translate to Portuguese: examples/serverless-builder

- examples/serverless-tomee-webprofile/README_pt.adoc
Translate to Portuguese the example serverless-tomee-webprofile
link to Jira: https://issues.apache.org/jira/browse/TOMEE-2964
> TOMEE-2964 Translate to Portuguese: examples/serverless-tomee-webprofile

- examples/schedule-expression/README_pt.adoc
Translate to Portuguese: examples/schedule-expression
Link to Jira: https://issues.apache.org/jira/browse/TOMEE-2978
> TOMEE-2978 Translate to Portuguese: examples/schedule-expression

- examples/simple-cmp2/README_pt.adoc
Translate to portuguese of exemple Simple-CMP2
Link to jira : https://issues.apache.org/jira/browse/TOMEE-2980
> TOMEE-2980 Translate to Portuguese: examples/simple-cmp2

- examples/simple-jms/README_pt.adoc
Translate portuguese example simple JMS
link to Jira: https://issues.apache.org/jira/browse/TOMEE-2981
> TOMEE2981 Translate to Portuguese: examples/simple-jms

- examples/simple-mdb/README_pt.adoc
Translate to portuguese example simple-mdb
Link to JIra: https://issues.apache.org/jira/browse/TOMEE-2983
> TOMEE-2983 Translate to Portuguese: examples/simple-mdb

- examples/simple-jms-context/README_pt.adoc
Translate to portuguese the example JMS context .
Link to JIra: https://issues.apache.org/jira/browse/TOMEE-2982
> TOMEE-2982 Translate to Portuguese: examples/simple-jms-context

- examples/simple-singleton/README_pt.adoc
- Translate to Portuguese
- fix in format code Java in Spanish
link to jira: https://issues.apache.org/jira/browse/TOMEE-2473
> TOMEE-2984 Translate to Portuguese: examples/simple-singleton

- examples/polling-parent/README_es.adoc
Translate to spanish, the document in english, README.adoc file.
> Spanish translation README.adoc file examples/polling-parent

- examples/rest-xml-json/README_es.adoc
In the path examples/rest-xml-json, translate to spanish the document README.adoc in the document README_es.adoc.
> Spanish translation README.adoc file examples/rest-xml-json

- container/openejb-core/src/main/java/org/apache/openejb/assembler/classic/JaccPermissionsBuilder.java
- container/openejb-core/src/main/java/org/apache/openejb/assembler/classic/PolicyContext.java
- container/openejb-core/src/main/java/org/apache/openejb/core/security/AbstractSecurityService.java
- container/openejb-core/src/main/java/org/apache/openejb/core/security/JaccProvider.java
- container/openejb-core/src/main/java/org/apache/openejb/core/security/jacc/BasicJaccProvider.java
- container/openejb-core/src/main/java/org/apache/openejb/ri/sp/PseudoSecurityService.java
- container/openejb-core/src/main/java/org/apache/openejb/spi/SecurityService.java
- tomee/apache-tomee/src/patch/java/org/apache/catalina/authenticator/jaspic/CallbackHandlerImpl.java
- tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/Contexts.java
- tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/TomcatSecurityService.java
- tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/TomcatWebAppBuilder.java
- tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/security/HTTPMethods.java
- tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/security/TomcatSecurityConstaintsToJaccPermissionsTransformer.java
- tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/security/URLPattern.java
- tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/security/URLPatternCheck.java
- tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/security/UncheckedItem.java
- tomee/tomee-security/src/main/java/org/apache/tomee/security/TomEESecurityContext.java
- tomee/tomee-security/src/main/java/org/apache/tomee/security/cdi/TomEESecurityExtension.java
- tomee/tomee-security/src/main/java/org/apache/tomee/security/identitystore/TomEEIdentityStoreHandler.java
- tomee/tomee-security/src/main/java/org/apache/tomee/security/provider/TomEESecurityServerAuthConfig.java
- tomee/tomee-security/src/main/java/org/apache/tomee/security/servlet/TomEESecurityServletContainerInitializer.java
- tomee/tomee-security/src/test/java/org/apache/tomee/security/servlet/JaccPermissionServletTest.java
- tomee/tomee-security/src/test/resources/conf/tomcat-users.xml
Some other fixes included. Test cases, etc
> TOMEE-3211 TOMEE-3212 Finish tomee-security to implement fully Jakarta Security API. 

- tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/TomcatWebAppBuilder.java
Throw exception, if deployment to unknown host is not possible.
> TOMEE-3797

- arquillian/arquillian-tomee-tests/arquillian-tomee-webprofile-tests/src/test/java/org/apache/openejb/arquillian/tests/cmp/sample/CustomOrmXmlHibernateEarTest.java
- arquillian/arquillian-tomee-tests/arquillian-tomee-webprofile-tests/src/test/resources/org/apache/openejb/arquillian/tests/cmp/sample/persistence-hibernate.xml
- arquillian/arquillian-tomee-tests/pom.xml
- container/openejb-jpa-integration/pom.xml
- examples/jpa-hibernate-arquillian/README.adoc
- examples/jpa-hibernate-arquillian/src/test/resources/arquillian.xml
- pom.xml
- utils/openejb-core-hibernate/pom.xml
Updates Hibernate to 5.6.7.
Currently having a full build on Jenkins - so let's what will happen.
> TOMEE-3872 - Update Hibernate Integration to 5.6.7

- boms/tomee-microprofile/pom.xml
- boms/tomee-plume/pom.xml
- container/openejb-core/pom.xml
- pom.xml
- tomee/tomee-microprofile/tomee-microprofile-webapp/pom.xml
- tomee/tomee-plume-webapp/pom.xml
batchee and jcs added in Plume to reflect Plus flavor
removed xml api from from Plume to reflect Plus flavor
remains some jar refs in jar scan exclusions (xerces, xml-apis)
> TOMEE-3871 - TomEE Plume is missing BatchEE / JCS Cache

- docs/comparison.adoc
- docs/documentation.adoc
- docs/documentation.old.adoc
this is the "per-version" comparison page for v8
> TOMEE-3846 Add Comparison page for TomEE v8

- boms/tomee-microprofile/pom.xml
- boms/tomee-plume/pom.xml
- boms/tomee-plus/pom.xml
- boms/tomee-webprofile/pom.xml
Signed-off-by: GitHub <noreply@github.com>
> Minor: Regenerated BOMs for 6e4e8277c26b9a31d86c3bbc1ce0002e041521b3

- container/openejb-core/src/main/java/org/apache/openejb/util/classloader/URLClassLoaderFirst.java
Restore use of JPA resources in server libraries
> TOMEE-3849

- container/openejb-jee/src/main/java/org/apache/openejb/jee/JaxbJavaee.java
- container/openejb-jee/src/main/java/org/apache/openejb/jee/ObjectFactory.java
- container/openejb-jee/src/test/java/org/apache/openejb/jee/JeeTest.java
- container/openejb-jee/src/test/resources/web-fragment-example.xml
I create a new method into ObjectFactory and a new test method, where unmarshalling the web-fragment.xml is successful.
Sorry I made a code format in JeeTest.java. 
Unfortunately I do not know how to test ObjectFactory.createWebFragment method.
> Tomee 3824

- boms/tomee-microprofile/pom.xml
- boms/tomee-plume/pom.xml
- boms/tomee-plus/pom.xml
- boms/tomee-webprofile/pom.xml
- container/openejb-core/src/main/java/org/apache/openejb/resource/jdbc/dbcp/BasicManagedDataSource.java
- container/openejb-core/src/main/java/org/apache/openejb/resource/jdbc/dbcp/DbcpManagedDataSource.java
- container/openejb-core/src/main/java/org/apache/openejb/resource/jdbc/dbcp/DbcpTransactionRegistry.java
- container/openejb-core/src/test/java/org/apache/openejb/resource/jdbc/XAPoolTest.java
- pom.xml
- Upgrade to DBCP v2.9.0
- https://ci-builds.apache.org/job/Tomee/job/TOMEE-3800
> TOMEE-3800 - DBCP 2.9.0

- boms/tomee-microprofile/pom.xml
- boms/tomee-plume/pom.xml
- boms/tomee-plus/pom.xml
- pom.xml
- tomee/tomee-microprofile/mp-common/pom.xml
MicroProfile 5.0 & SmallRye Fault Tolerance 6.0.0 instead of RC
Fixed Copy paste error for Metrics
> [TOMEE-4035] - MicroProfile 5.0

- examples/mvc-cxf/pom.xml
- examples/mvc-resteasy/pom.xml
- pom.xml
[TOMEE-4052] - SAAJ Impl 2.0.1 => see https://issues.apache.org/jira/browse/TOMEE-4052
Krazo 2.0.2 => same for both EE 9.1 and 10.0 !
CXF 3.5.3
MP Config 3.0.2
MP FT 4.0.1
Log4J 2.19.0
> [TOMEE-4035] Jakarta 9.1.0 and MicroProfile 5.0

- arquillian/arquillian-tomee-tests/arquillian-tomee-webprofile-tests/pom.xml
- examples/deltaspike-configproperty/pom.xml
- examples/deltaspike-exception-handling/pom.xml
- examples/deltaspike-fullstack/pom.xml
- examples/deltaspike-i18n/pom.xml
- examples/mvc-cxf-hibernate/pom.xml
- examples/mvc-cxf/pom.xml
- examples/mvc-resteasy/pom.xml
- examples/mvc-resteasy/src/test/resources/a-pom.xml
- examples/pom.xml
- itests/openejb-itests-beans/pom.xml
- maven/tomee-webapp-archetype/pom.xml
- pom.xml
Updates :
- Krazo 1.1.1
- DeltaSpike 1.9.6
- EclipseLink 2.7.11
- Hibernate 5.6.12.Final
> [TOMEE-4058] Update Krazo to 1.1.1 and DeltaSpike to 1.9.6

- pom.xml
this branch has the properties re-ordered/regrouped by categories, but without name changes, so normally no impact on ci build.
> [TOMEE-4053] Dependency properties cleanup, step 1 on branch 8.x

- pom.xml
this one has some properties renamed, only when they are used within the same root pom.
these name changes may be tested against ci tests if needed.
> [TOMEE-4053] Dependency properties cleanup, step 2 on branch 8.x

- docs/configuring-datasources-xa.adoc
[TOMEE-4104](https://issues.apache.org/jira/browse/TOMEE-4104). Added missing &lt;/Resource&gt; tag to MySQL example code.
> TOMEE-4104 - Fixed bug in MySQL example code.

- boms/tomee-microprofile/pom.xml
- boms/tomee-plume/pom.xml
- boms/tomee-plus/pom.xml
- pom.xml
Update dependency: Jackson 2.14.0
> [TOMEE-4107] Update TomEE 8.x dependency: Jackson 2.14.0

- boms/tomee-microprofile/pom.xml
- boms/tomee-plume/pom.xml
- boms/tomee-plus/pom.xml
- pom.xml
Update dependency: Jackson 2.14.0
> [TOMEE-4107] Update TomEE 9.x dependency: Jackson 2.14.0

- assembly/pom.xml
- boms/pom.xml
- deps/commons-dbcp2-shade/pom.xml
- deps/commons-fileupload-shade/pom.xml
- deps/pom.xml
- itests/pom.xml
- pom.xml
- tck/pom.xml
- tomee/tomee-plume-webapp/pom.xml
- tomee/tomee-plus-webapp/pom.xml
- tomee/tomee-webapp/pom.xml
this branch has the properties re-ordered/regrouped by categories, with name changes, we can test this on ci build.
> [TOMEE-4053] Dependency properties cleanup, step 1 and 2 on branch 9.x

- itests/tomee-security-itests/src/test/java/org/apache/tomee/security/itest/FormAuthConfig.java
- itests/tomee-security-itests/src/test/java/org/apache/tomee/security/itest/LoginToContinueTest.java
> add integration test case for @LoginToContinue with form auth

- mp-jwt/pom.xml
- pom.xml
- tck/microprofile-tck/config/pom.xml
- tck/microprofile-tck/fault-tolerance/pom.xml
- tck/microprofile-tck/health/pom.xml
- tck/microprofile-tck/jwt/pom.xml
- tck/microprofile-tck/metrics/pom.xml
- tck/microprofile-tck/openapi/pom.xml
- tck/microprofile-tck/opentracing/pom.xml
- tck/microprofile-tck/pom.xml
- tck/microprofile-tck/rest-client/pom.xml
- tomee/tomee-microprofile/mp-common/pom.xml
this one is about tck tests and microprofile api & impl.
> [TOMEE-4053] Dependency properties cleanup, step 3 on branch 8.x

- arquillian/arquillian-tomee-embedded/pom.xml
- arquillian/arquillian-tomee-moviefun-example/pom.xml
- arquillian/arquillian-tomee-remote/pom.xml
- arquillian/arquillian-tomee-tests/arquillian-tomee-jms-tests/pom.xml
- container/openejb-core/pom.xml
- deps/cxf-shade/pom.xml
- itests/ejb/pom.xml
- pom.xml
- server/openejb-cxf-rs/pom.xml
- server/openejb-cxf-transport/pom.xml
- server/openejb-cxf/pom.xml
- server/openejb-webservices/pom.xml
- tck/cdi-embedded/pom.xml
- tck/cdi-tomee/pom.xml
- tck/cdi-tomee/src/test/resources/arquillian.xml
- tck/microprofile-tck/jwt/pom.xml
- tck/microprofile-tck/openapi/pom.xml
- tck/microprofile-tck/rest-client/pom.xml
- tomee/apache-tomee/pom.xml
- tomee/pom.xml
- tomee/tomee-microprofile/mp-common/pom.xml
- tomee/tomee-microprofile/tomee-microprofile-webapp/pom.xml
- tomee/tomee-myfaces/pom.xml
- tomee/tomee-plume-webapp/pom.xml
- tomee/tomee-plus-webapp/pom.xml
- tomee/tomee-webapp/pom.xml
- utils/openejb-core-hibernate/pom.xml
this one is renaming Jakarta EE version properties
> [TOMEE-4053] Dependency properties cleanup, step 4 on branch 8.x

- itests/pom.xml
- itests/tomee-security-itests/pom.xml
- itests/tomee-security-itests/src/test/java/org/apache/tomee/security/itest/AnotherAuthMechanism.java
- itests/tomee-security-itests/src/test/java/org/apache/tomee/security/itest/AuthMechanism.java
- itests/tomee-security-itests/src/test/java/org/apache/tomee/security/itest/FormAuthConfig.java
- itests/tomee-security-itests/src/test/java/org/apache/tomee/security/itest/LoginToContinueTest.java
- tomee/tomee-security/src/main/java/org/apache/tomee/security/cdi/LoginToContinueInterceptor.java
- tomee/tomee-security/src/main/java/org/apache/tomee/security/cdi/TomEESecurityServletAuthenticationMechanismMapper.java
> TOMEE-4108 - Backport TOMEE-4065: LoginToContinue interceptor fails on custom auth mechanism

- pom.xml
- tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/LazyStopStandardRoot.java
TomEE 8.x dependency update to tomcat 9.0.69 (EE 8)
> [TOMEE-4115] Tomcat update to 9.0.69

- deps/pom.xml
- deps/servicemix-bcel-shade/pom.xml
- deps/servicemix-bcel-shade/src/patch/java/org/apache/bcel/classfile/ConstantPool.java
- deps/servicemix-bcel-shade/src/patch/java/org/apache/bcel/generic/ConstantPoolGen.java
- server/openejb-client/pom.xml
as the title says: https://issues.apache.org/jira/browse/TOMEE-4111
> TOMEE-4111 - Patch shaded bcel in servicemix.bcel needed by yoko (8.x)

- deps/pom.xml
- deps/servicemix-bcel-shade/pom.xml
- deps/servicemix-bcel-shade/src/patch/java/org/apache/bcel/classfile/ConstantPool.java
- deps/servicemix-bcel-shade/src/patch/java/org/apache/bcel/generic/ConstantPoolGen.java
- server/openejb-client/pom.xml
as the title says: https://issues.apache.org/jira/browse/TOMEE-4111
> TOMEE-4111 - Patch shaded bcel in servicemix.bcel needed by yoko (9.x)

- tomee/pom.xml
- tomee/tomee-embedded/pom.xml
- tomee/tomee-embedded/src/main/java/org/apache/tomee/embedded/Container.java
Update dependency
* velocity 2.3
> [TOMEE-4109] TomEE 8.x Update velocity to 2.3 and avoid CVE warnings

- tomee/pom.xml
- tomee/tomee-embedded/pom.xml
- tomee/tomee-embedded/src/main/java/org/apache/tomee/embedded/Container.java
Update dependency
* velocity 2.3
> [TOMEE-4109] TomEE 9.x Update velocity to 2.3 and avoid CVE warnings

- pom.xml
as the title says
no changes in patched classes: https://github.com/apache/cxf/compare/cxf-3.5.4...cxf-3.5.5
> TOMEE-4127 - CXF 3.5.5

- deps/cxf-rt-rs-mp-client-shade/pom.xml
- examples/mp-config-example/pom.xml
- examples/mp-custom-healthcheck/pom.xml
- examples/mp-faulttolerance-fallback/pom.xml
- examples/mp-faulttolerance-retry/pom.xml
- examples/mp-faulttolerance-timeout/pom.xml
- examples/mp-metrics-counted/pom.xml
- examples/mp-metrics-gauge/pom.xml
- examples/mp-metrics-histogram/pom.xml
- examples/mp-metrics-metered/pom.xml
- examples/mp-metrics-timed/pom.xml
- examples/mp-rest-client/README.adoc
- examples/mp-rest-client/README_es.adoc
- examples/mp-rest-client/README_pt.adoc
- examples/mp-rest-client/pom.xml
- itests/microprofile-jwt-itests/pom.xml
- itests/tomee-microprofile-itests/pom.xml
- mp-jwt/pom.xml
- pom.xml
- tck/microprofile-tck/config/pom.xml
- tck/microprofile-tck/fault-tolerance/pom.xml
- tck/microprofile-tck/health/pom.xml
- tck/microprofile-tck/jwt/pom.xml
- tck/microprofile-tck/metrics/pom.xml
- tck/microprofile-tck/openapi/pom.xml
- tck/microprofile-tck/opentracing/pom.xml
- tck/microprofile-tck/pom.xml
- tck/microprofile-tck/rest-client/pom.xml
- tomee/tomee-microprofile/mp-common/pom.xml
[TOMEE-4053] Dependency properties cleanup, step 3 : Micro Profile properties on branch main/10.x
Edit: now without changes to the versions numbers
> [TOMEE-4053] Dependency properties cleanup, step 3 : Micro Profile properties on branch main/10.x

- container/openejb-core/src/test/java/org/apache/openejb/resource/jdbc/driver/AlternateDriverJarTest.java
- examples/xa-datasource/pom.xml
- pom.xml
This is a tentative to update Derby to 10.15.x, upon other dep updates.
Derby 10.15.x is modular, it might break CI, please merge wisely.
TomEE 9.x dependencies update: 
* Derby 10.15.2.0
> [TOMEE-4061] Derby 10.15.2.0, branch 10.x

- container/openejb-junit5/src/test/java/org/apache/openejb/junit5/AppComposerPerClassBase.java
- container/openejb-junit5/src/test/java/org/apache/openejb/junit5/AppComposerPerClassInheritanceTest.java
- container/openejb-junit5/src/test/java/org/apache/openejb/junit5/AppComposerSnifferExtension.java
- Added Inherited annotation.
- Added unittests to proove fix.
> TOMEE-4190 RunWithApplicationComposer should support inheritance

- container/openejb-core/src/main/java/org/apache/openejb/testing/ApplicationComposers.java
- container/openejb-junit5/src/test/java/org/apache/openejb/junit5/AppComposerMemoryReleaseTest.java
https://github.com/apache/tomee/pull/1030
> TOMEE-4192 - ApplicationComposers do not clear GC references on release 

- boms/tomee-microprofile/src/main/resources/tomee/conf/server.xml
- boms/tomee-plume/src/main/resources/tomee/conf/server.xml
- boms/tomee-plus/src/main/resources/tomee/conf/server.xml
- boms/tomee-webprofile/src/main/resources/tomee/conf/server.xml
- tomee/apache-tomee/src/patch/java/org/apache/catalina/Globals.java
- tomee/apache-tomee/src/patch/java/org/apache/catalina/connector/Request.java
- tomee/apache-tomee/src/patch/java/org/apache/catalina/filters/RemoteIpFilter.java
- tomee/apache-tomee/src/patch/java/org/apache/tomcat/util/http/Parameters.java
- tomee/apache-tomee/src/patch/java/org/apache/tomcat/util/http/fileupload/FileUploadBase.java
- tomee/apache-tomee/src/patch/java/org/apache/tomcat/util/http/fileupload/impl/FileCountLimitExceededException.java
- tomee/tomee-common/src/main/java/org/apache/tomee/installer/Installer.java
This PR 
1. patches Tomcat 10.0.27 for CVE-2023-28708 by applying the changeset from https://github.com/apache/tomcat/commit/f509bbf31fc00abe3d9f25ebfabca5e05173da5b
2. patches Tomcat 10.0.27 for CVE-2023-24998 by applying the changeset from https://github.com/apache/tomcat/commit/8a2285f13affa961cc65595aad999db5efae45ce
3. adds the related patch: https://github.com/apache/tomcat/commit/ba848da71c523d94950d3c53c19ea155189df9dc regarding parameter counting related to 2.
Triggered a full build on https://ci-builds.apache.org/job/Tomee/job/pull-request-9.x-manual/ for it.
> TOMEE-4202 - Patch Tomcat 10.0.27 with fixes for CVE-2023-24998 & CVE-2023-28708 

- boms/tomee-microprofile/pom.xml
- boms/tomee-plume/pom.xml
- boms/tomee-plus/pom.xml
- mp-jwt/pom.xml
https://ci-builds.apache.org/job/Tomee/job/pull-request-8.x-manual-java8/8/
> TOMEE-4205 - Upgrade to Jose4j 0.9.3

- boms/tomee-plume/pom.xml
- boms/tomee-plus/pom.xml
- pom.xml
- tomee/apache-tomee/pom.xml
https://ci-builds.apache.org/job/Tomee/job/pull-request-8.x-manual-java8/10/
> TOMEE-4188 - ActiveMQ 5.16.6

- boms/tomee-microprofile/pom.xml
- boms/tomee-plume/pom.xml
- boms/tomee-plus/pom.xml
- pom.xml
https://ci-builds.apache.org/job/Tomee/job/pull-request-8.x-manual-java8/11
> TOMEE-4206 - Upgrade to Jackson 2.15.0

- boms/tomee-microprofile/pom.xml
- boms/tomee-plume-api/pom.xml
- boms/tomee-plume/pom.xml
- boms/tomee-plus/pom.xml
- boms/tomee-webprofile/pom.xml
- pom.xml
- TOMEE-4207 - Johnzon 1.2.20 
- TOMEE-4209 - Mojarra 2.3.19]
- TOMEE-4211 - Hibernate Integration 5.6.15.Final
- TOMEE-4210 - EclipseLink 2.7.12
- 
https://ci-builds.apache.org/job/Tomee/job/pull-request-8.x-manual-java8/12
> TOMEE-4207, TOMEE-4209,  TOMEE-4210,  TOMEE-4211 - Johnzon, Mojarra, EclipseLink, Hibernate Integration

- boms/tomee-microprofile/pom.xml
- boms/tomee-plume/pom.xml
- boms/tomee-plus/pom.xml
- boms/tomee-webprofile/pom.xml
- pom.xml
- TOMEE-4212 - Jackson 2.15.0 
- TOMEE-4208 - Johnzon 1.2.20
https://ci-builds.apache.org/job/Tomee/job/pull-request-9.x-manual/12/
> TOMEE-4208, TOMEE-4212 - Johnzon, Jackson

- tomee/apache-tomee/src/patch/java/org/apache/coyote/ajp/AjpProcessor.java
- tomee/apache-tomee/src/patch/java/org/apache/coyote/ajp/LocalStrings.properties
Backports the fix for CVE-2023-34981 from Tomcat 10.1.x + some related formatting fixes.
> TOMEE-4230 - Backport fix for CVE-2023-34981

- tomee/apache-tomee/pom.xml
- tomee/apache-tomee/src/patch/java/org/apache/catalina/connector/LocalStrings.properties
- tomee/apache-tomee/src/patch/java/org/apache/catalina/connector/Request.java
- tomee/apache-tomee/src/patch/java/org/apache/catalina/core/ApplicationHttpRequest.java
- tomee/apache-tomee/src/patch/java/org/apache/catalina/core/LocalStrings.properties
- tomee/apache-tomee/src/patch/java/org/apache/coyote/http11/Http11InputBuffer.java
- tomee/apache-tomee/src/patch/java/org/apache/coyote/http11/filters/ChunkedInputFilter.java
- tomee/apache-tomee/src/patch/java/org/apache/coyote/http11/filters/LocalStrings.properties
- tomee/apache-tomee/src/patch/java/org/apache/coyote/http2/Http2AsyncParser.java
- tomee/apache-tomee/src/patch/java/org/apache/coyote/http2/Http2Protocol.java
- tomee/apache-tomee/src/patch/java/org/apache/coyote/http2/Http2UpgradeHandler.java
- tomee/apache-tomee/src/patch/java/org/apache/tomcat/util/buf/B2CConverter.java
- tomee/apache-tomee/src/patch/java/org/apache/tomcat/util/buf/C2BConverter.java
- tomee/apache-tomee/src/patch/java/org/apache/tomcat/util/buf/LocalStrings.properties
- see https://tomcat.apache.org/security-10.html#Fixed_in_Apache_Tomcat_10.1.14
------------
- https://issues.apache.org/jira/browse/TOMEE-4254
- https://issues.apache.org/jira/browse/TOMEE-4255
- https://issues.apache.org/jira/browse/TOMEE-4256
--------------
- full build (running): https://ci-builds.apache.org/job/Tomee/view/tomee-9.x/job/pull-request-9.x-manual/24/
> Backports the fixes contained in Tomcat 10.1.14 to TomEE 9.x

- itests/ejb/pom.xml
> Fixed version and build

- pom.xml
- tomee/tomee-microprofile/mp-common/pom.xml
- tomee/tomee-microprofile/mp-common/src/main/java/org/apache/tomee/microprofile/health/MPHealthCDIExtension.java
OWB contains new 2 fixes, one is necessary for JSF applications as some ELs are not resolveable anymore
> Improve failed startup follow-up exceptions and back to OWB snapshot

- tomee/tomee-microprofile/mp-common/pom.xml
New dependency tree with the following exclusions:
- CDI/JSON-P
- glassfish json/parsson -> We should use johnzon instead
- smallrye-health-api -> custom [vendor specific API](https://github.com/smallrye/smallrye-health/tree/release-4.0.1/api) of smallrye, imho this shouldn't be a transitive dependency at all
```
➜ mvn dependency:tree
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< org.apache.tomee:mp-common >---------------------
[INFO] Building TomEE :: TomEE :: MicroProfile Common 9.1.3-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- dependency:3.3.0:tree (default-cli) @ mp-common ---
[INFO] org.apache.tomee:mp-common:jar:9.1.3-SNAPSHOT
[INFO] +- …
```
> Backport #1092 to tomee-9.x

- tomee/tomee-microprofile/mp-common/src/main/java/org/apache/tomee/microprofile/TomEEMicroProfileListener.java
> Backport TOMEE-4295 to 9.x

- mp-jwt/src/main/java/org/apache/tomee/microprofile/jwt/cdi/ClaimBean.java
- mp-jwt/src/main/java/org/apache/tomee/microprofile/jwt/cdi/TomeeMpJwt.java
resolves https://issues.apache.org/jira/browse/TOMEE-4350 by backporting #1189 to tomee-9.x
> TOMEE-4350 add qualifier for produced Jsonb (tomee-9.x)

- mp-jwt/src/main/java/org/apache/tomee/microprofile/jwt/cdi/ClaimBean.java
- mp-jwt/src/main/java/org/apache/tomee/microprofile/jwt/cdi/JsonbProducer.java
- mp-jwt/src/main/java/org/apache/tomee/microprofile/jwt/cdi/TomeeMpJwt.java
resolves https://issues.apache.org/jira/browse/TOMEE-4350
> TOMEE-4350 add qualifier for produced Jsonb

- examples/bval-evaluation-redeployment/pom.xml
- examples/jsf-cdi-and-ejb/pom.xml
- examples/jsf-managedBean-and-ejb/pom.xml
Update the Apache MyFaces to version 4.0.2, and update Apache DeltaSpike to version 2.0.0
> TOMEE-3965 - Update the Apache MyFaces and Apache DeltaSpike

- tomee/tomee-microprofile/mp-common/src/main/java/org/apache/tomee/microprofile/TomEEMicroProfileListener.java
Add a Jandex index cache to TomEEMicroProfileListener
This will fix a issue with a longer startup time since TomEE 9
The processApplication method is called for every created application and will then create an index for all jars.
But the index is based on the AppInfo of the application. The AppInfo can have multiple applications.
So currently the same index is created for every single application which is unnecessary
This change will boost our start up time from 2min to ~45s
> TOMEE-4357 - Add Jandex Index cache

- boms/tomee-microprofile/pom.xml
- boms/tomee-plume/pom.xml
- boms/tomee-plus/pom.xml
- boms/tomee-webprofile/pom.xml
- pom.xml
Resolves [TOMEE-4370](https://issues.apache.org/jira/browse/TOMEE-4370)
> [TOMEE-4370] CXF 4.0.5

- container/openejb-loader/src/main/java/org/apache/openejb/loader/TomcatClassPath.java
- tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/TomcatWebAppBuilder.java
- tomee/tomee-webapp/src/main/assembly/war.xml
TomcatClassPath.java: fix call of a wrong method and thus the resulting NPE
TomcatWebAppBuilder.java: fix NPE
war.xml: fix non-functioning display of the tomee installer webapp
> TOMEE-4404 - fix broken tomee-webapp

- tomee/tomee-microprofile/tomee-microprofile-webapp/pom.xml
- tomee/tomee-plume-webapp/pom.xml
- tomee/tomee-plus-webapp/pom.xml
- tomee/tomee-webapp/pom.xml
https://issues.apache.org/jira/browse/TOMEE-3724
> Remove TomEE drop-in webapp distributions

- arquillian/arquillian-openejb-embedded/pom.xml
- arquillian/arquillian-tomee-embedded/pom.xml
- tomee/tomee-webaccess/pom.xml
See https://issues.apache.org/jira/browse/TOMEE-4440
> TOMEE-4440 - fix scope for arquillian junit container

- container/openejb-core/src/main/java/org/apache/openejb/cdi/OWBContextThreadListener.java
- container/openejb-core/src/main/java/org/apache/openejb/cdi/RequestScopedThreadContextListener.java
- container/openejb-core/src/main/java/org/apache/openejb/core/ThreadContext.java
- container/openejb-core/src/main/java/org/apache/openejb/core/ThreadContextListener.java
- container/openejb-core/src/main/java/org/apache/openejb/core/ivm/BaseEjbProxyHandler.java
- container/openejb-core/src/main/java/org/apache/openejb/core/security/AbstractSecurityService.java
- container/openejb-core/src/main/java/org/apache/openejb/core/transaction/EjbTransactionUtil.java
- container/openejb-core/src/main/java/org/apache/openejb/core/transaction/TxPropagationTest.java
- container/openejb-core/src/main/java/org/apache/openejb/threads/impl/ApplicationThreadContextProvider.java
- container/openejb-core/src/main/java/org/apache/openejb/threads/impl/SecurityThreadContextProvider.java
- tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/TomcatThreadContextListener.java
For discussion on the mailing list. This addresses an issue where a transaction is incorrectly propagated to threads servicing a ManagedExecutorService.
> TOMEE-4483
