container/openejb-core/src/main/java/org/apache/openejb/core/mdb/MdbContainer.java
container/openejb-core/src/main/java/org/apache/openejb/resource/activemq/ActiveMQResourceAdapter.java
container/openejb-core/src/test/java/org/apache/openejb/resource/activemq/ActiveMQResourceAdapterControlTest.java

Backported from master, with a couple of tweaks for Java 6. This allows MDBs to stopped and started via JMX.

TOMEE-2021 - Backport control of listening state via JMX

---

server/openejb-client/pom.xml
server/openejb-cxf/pom.xml
tomee/tomee-embedded/pom.xml

https://issues.apache.org/jira/browse/TOMEE-2042
bcprov is included as a transient dependency for `openejb-cxf` module. This forces a secure version. I plan on logging bugs for wss4j and opensaml to upgrade the dependency.
```
[INFO] +- org.apache.wss4j:wss4j-ws-security-dom:jar:2.1.9:compile
[INFO] |  \- org.apache.wss4j:wss4j-ws-security-common:jar:2.1.9:compile
[INFO] |     +- org.apache.santuario:xmlsec:jar:2.0.6:compile
[INFO] |     |  \- commons-codec:commons-codec:jar:1.10:compile
[INFO] |     +- org.opensaml:opensaml-saml-impl:jar:3.1.1:compile
[INFO] |     |  +- org.opensaml:opensaml-profile-api:jar:3.1.1:compile
[INFO] |     |  |  \- org.opensaml:opensaml-core:jar:3.1.1:compile
[INFO] |     |  +- org.opensaml:opensaml-saml-api:jar:3.1.1:compile
[INFO] |     |  |  +- …
```

[WIP] [TOMEE-2042] Force upgrade of bcprov to fix 10 CVEs

---

arquillian/arquillian-tomee-webapp-remote/src/test/java/org/apache/openejb/arquillian/TomEEContainerEarWithExplodedWarTest.java
tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/TomcatWebAppBuilder.java

When in the EAR file, the web application's binaries are a directory
and the directory name ends with .war, do not handle it as a file.
With the current implementation the exception below is thrown. Note that the name of the directory inside of EAR file is `test.war` and not `test`.
```
07-Jun-2017 23:33:34.961 SEVERE [ContainerBackgroundProcessor[StandardEngine[Catalina]]] sun.reflect.NativeMethodAccessorImpl.invoke ContainerBase.addChild: start: 
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/test]]
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
at …
```

When in EAR, the web app doc base is a directory ending with .war do not handle it as a file

---

container/openejb-core/src/main/java/org/apache/openejb/config/AutoConfig.java

Fix the sorting issue, by removing the sorting operation. We are not interested in the order of the elements, but only in the smallest element.
Two improvements:
1. Do not unnecessary allocate a new array list
2. Collections.min() is O(n) vs O(nLog(n) for sort() (well without counting indexOf() in the comparator)

Fix TomEE-2085

---

arquillian/arquillian-tomee-tests/arquillian-tomee-webprofile-tests/src/test/java/org/apache/openejb/arquillian/tests/naming/IvmContextServlet.java
arquillian/arquillian-tomee-tests/arquillian-tomee-webprofile-tests/src/test/java/org/apache/openejb/arquillian/tests/naming/IvmContextTest.java
arquillian/arquillian-tomee-tests/arquillian-tomee-webprofile-tests/src/test/java/org/apache/openejb/arquillian/tests/naming/NamingBean.java

With the removal of the boiler-plate servlet, the test is not executed
against the correct context and does not test what it was intended
to test.

Revert "Simplify Test"

---

pom.xml

Updates CXF version based on the CVE: http://cxf.apache.org/security-advisories.data/CVE-2018-8039.txt.asc?version=1&modificationDate=1530184663000&api=v2

updates cxf to version 3.1.16

---

container/openejb-core/src/main/java/org/apache/openejb/assembler/classic/JndiEncBuilder.java
container/openejb-core/src/main/java/org/apache/openejb/core/ivm/naming/MapObjectReference.java
server/openejb-cxf-rs/src/main/java/org/apache/openejb/server/cxf/rs/Contexts.java
server/openejb-cxf-rs/src/test/java/org/apache/openejb/server/cxf/rs/ApplicationRsInjectionTest.java

There are two things here:
* the `javax.ws.rs.core.Application` option was not in the if chain in JndiEncBuilder.java.
* MapObjectReference.java was throwing NPE if the referenced map was null. 
Help on creating unit tests for these guys is needed.

[TOMEE-2201] NPE when injecting Application

---

pom.xml

The error was
`java.lang.NoSuchMethodError: 
org.apache.xml.security.utils.XMLUtils.encodeToString([B)Ljava/lang/String; 
at 
org.apache.wss4j.dom.message.token.UsernameToken.addNonce(UsernameToken.java:303) 
at 
org.apache.wss4j.dom.message.token.UsernameToken.<init>(UsernameToken.java:264) 
at 
org.apache.wss4j.dom.message.WSSecUsernameToken.prepare(WSSecUsernameToken.java:168) 
at 
org.apache.wss4j.dom.message.WSSecUsernameToken.build(WSSecUsernameToken.java:225) 
at 
org.apache.wss4j.dom.action.UsernameTokenAction.execute(UsernameTokenAction.java:69) 
at 
org.apache.wss4j.dom.handler.WSHandler.doSenderAction(WSHandler.java:238) 
at 
org.apache.cxf.ws.security.wss4j.WSS4JOutInterceptor.access$100(WSS4JOutInterceptor.java:57) 
at …

upgrade xmlsec dependency to fix incompatibility issue with wss4j 2.2.2

---

container/openejb-core/src/main/java/org/apache/openejb/assembler/classic/Assembler.java
container/openejb-core/src/main/java/org/apache/openejb/monitoring/ConnectionFactoryMonitor.java
container/openejb-core/src/main/java/org/apache/openejb/monitoring/MBeanPojoWrapper.java
container/openejb-core/src/main/java/org/apache/openejb/resource/GeronimoConnectionManagerFactory.java
container/openejb-core/src/test/java/org/apache/openejb/assembler/classic/ConnectionFactoryJMXTest.java
container/openejb-core/src/test/java/org/apache/openejb/assembler/classic/ResourcesJMXTest.java

Backport this to 7.0.x
https://github.com/apache/tomee/pull/160/files

Apply Jonathan Gallimore's JMX Patch to 7.0.5

---

container/openejb-core/src/main/java/org/apache/openejb/core/singleton/SingletonEjbObjectHandler.java

While I was studying the code, I found at SingletonEjbObjectHandler.java that they are creating a new Boolean instance instead of using the `Boolean.valueOf.` method.
The boolean wrapper has a singleton instance to both true and false. However, it will use when the code uses the Boolean.valueOf method.
Beyond the waste of memory, because they're creating a new `boolean` instance every time, it will be slower than the `valueOf` method.
```java
@Warmup(iterations = 5, time = 1, timeUnit = TimeUnit.SECONDS)
@Measurement(iterations = 20, time = 1, timeUnit = TimeUnit.SECONDS)
@Fork(3)
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@State(Scope.Thread)
public class FasterReflectionClientBenchmark {
private ThreadLocalRandom random = ThreadLocalRandom.current(); …
```

Uses Boolean.valueof instaed of new instance

---

container/openejb-core/src/main/java/org/apache/openejb/assembler/classic/Assembler.java
container/openejb-core/src/main/java/org/apache/openejb/config/AnnotationDeployer.java
container/openejb-core/src/main/java/org/apache/openejb/config/SunConversion.java
container/openejb-core/src/main/java/org/apache/openejb/monitoring/ObjectNameBuilder.java
container/openejb-core/src/main/java/org/apache/openejb/resource/AutoConnectionTracker.java
container/openejb-core/src/main/java/org/apache/openejb/resource/jdbc/logging/LoggingPreparedSqlStatement.java
container/openejb-loader/src/main/java/org/apache/openejb/loader/provisining/MavenResolver.java
tomee/tomee-webapp/src/main/java/org/apache/tomee/webapp/installer/InstallerServlet.java

The reason to prefer StringBuilder is that both + and concat create a new object every time you call them (provided the right-hand side argument is not empty). This can quickly add up to a lot of objects, almost all of which are completely unnecessary.
```java
public class Main
{
public static void main(String[] args)
{
long now = System.currentTimeMillis();
slow();
System.out.println("slow elapsed " + (System.currentTimeMillis() - now) + " ms");
now = System.currentTimeMillis();
fast();
System.out.println("fast elapsed " + (System.currentTimeMillis() - now) + " ms");
}
private static void fast()
{
StringBuilder s = new StringBuilder();
for(int i=0;i<100000;i++)
s.append("*");      
}
private static void slow()
{
String s = "";
for(int i=0;i<100000;i++)
s+="*";
}
}
```
* slow elapsed …

Avoid String in a loop

---

examples/mp-metrics-timed/README.md
examples/quartz-app/README.md
examples/realm-in-tomee/README.md
examples/reload-persistence-unit-properties/README.md

I've noticed that some of the README.mb files have text that could be improved. These commits improve the text on those examples.

Fixing documentation on some of the examples

---

.gitignore
arquillian/arquillian-tomee-tests/arquillian-tomee-webprofile-tests/src/test/java/org/apache/openejb/arquillian/tests/cmp/CmpMappingTest.java
arquillian/arquillian-tomee-tests/arquillian-tomee-webprofile-tests/src/test/java/org/apache/openejb/arquillian/tests/cmp/CmpServlet.java
arquillian/arquillian-tomee-tests/arquillian-tomee-webprofile-tests/src/test/java/org/apache/openejb/arquillian/tests/cmp/MyCmpBean.java
arquillian/arquillian-tomee-tests/arquillian-tomee-webprofile-tests/src/test/java/org/apache/openejb/arquillian/tests/cmp/MyLocalHome.java
arquillian/arquillian-tomee-tests/arquillian-tomee-webprofile-tests/src/test/java/org/apache/openejb/arquillian/tests/cmp/MyLocalObject.java
arquillian/arquillian-tomee-tests/arquillian-tomee-webprofile-tests/src/test/java/org/apache/openejb/arquillian/tests/cmp/MyRemoteHome.java
arquillian/arquillian-tomee-tests/arquillian-tomee-webprofile-tests/src/test/java/org/apache/openejb/arquillian/tests/cmp/MyRemoteObject.java
arquillian/arquillian-tomee-tests/arquillian-tomee-webprofile-tests/src/test/resources/org/apache/openejb/arquillian/tests/cmp/ejb-jar.xml
arquillian/arquillian-tomee-tests/arquillian-tomee-webprofile-tests/src/test/resources/org/apache/openejb/arquillian/tests/cmp/openejb-cmp-orm.xml
container/openejb-core/src/main/java/org/apache/openejb/config/ReadDescriptors.java
container/openejb-core/src/test/java/org/apache/openejb/config/ReadDescriptorsTest.java
container/openejb-core/src/test/java/org/apache/openejb/core/LegacyInterfaceTest.java
container/openejb-core/src/test/java/org/apache/openejb/core/webservices/JPACMDIntegrationTest.java
container/openejb-core/src/test/resources/org/apache/openejb/config/test-openejb-cmp-orm.xml
container/openejb-jee/src/main/java/org/apache/openejb/jee/JaxbJavaee.java

We found an error when using CMP; when the container starts, it returns an unmarshal error:
```java
at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:662)
at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:258)
at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:253)
at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportUnexpectedChildElement(Loader.java:120)
at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.childElement(Loader.java:105)
at com.sun.xml.bind.v2.runtime.unmarshaller.StructureLoader.childElement(StructureLoader.java:262)
at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:498)
at …
```

Creates an unmarshal that does not filter to JavaEE namespace

---

owasp-dc-suppression.xml
pom.xml

This PR introduces the [OWASP Dependency Check Maven Plugin](https://jeremylong.github.io/DependencyCheck/index.html) in a basic configuration at the parent pom level of the project.
As the dependency checking is quite expensive (see time below), I added it is a separate profile `owasp`. To enable it in the Maven build process, you just need to add `-Powasp-report` or `-Powasp-check`. 
An aggregated report `dependency-check-report.html` is created in the target directory of the root project (only in acse you enabled `-Powasp-report`)
I also added some exclusions related to false positives (see `owasp-dc-suppression.xml`).
I also added the aggregated output for the run on my second system: [dependency-check-report.zip](https://github.com/apache/tomee/files/2690169/dependency-check-report.zi …

TOMEE-2363 Introduces OWASP dependency check via profile

---

tomee/apache-tomee/src/main/resources/service.bat

When JAVA_HOME is set to a path with a space (e.g. C:\Program Files\Java\jdk11.0.1), I get this error:
```
C:\Program Files\TomEE\bin>service install
11 was unexpected at this time.
```
This is introduced with #178. I fixed it by adding quotes to the path.
Bonus: removal of superfluous tokens which are not used.

Fixes TOMEE-2261 Make service.bat compatible with JDK11+

---

examples/cdi-session-scope/README.md

Added README.md to cdi-session-scope/.

TOMEE-2373 Add README.adoc to cdi-session-scope/

---

container/openejb-core/pom.xml
pom.xml

This starts this task off, introducing the plugin at the root level under pluginManagement, and using it in a `coverage` profile on openejb-core.
There's a handful of tests that fail with Jacoco, so we may wish to either find a fix, or split them into a separate execution that does not include jacoco.

TOMEE-2436 Get code coverage report from JaCoCo

---

examples/simple-cmp2/pom.xml

When running against snapshot build dependency must be copied with it's base version.

Copy dependency with base version

---

arquillian/arquillian-tomee-tests/arquillian-tomee-jms-tests/src/test/java/org/apache/openejb/arquillian/tests/jms/EnvEntryTest.java
container/openejb-core/src/main/java/org/apache/openejb/assembler/classic/Assembler.java
container/openejb-core/src/main/java/org/apache/openejb/cdi/OWBContextThreadListener.java

Now new code checks if there is no WebBeansContext it places special holder as marker so when contextExited is called it will know that there is no need to restore previous context.
I've also enabled the EnvEntryTest which works.
There is also one typo fix in Assembler class in openejb-core.

Fix for https://issues.apache.org/jira/browse/TOMEE-2448

---

examples/mp-metrics-counted/Dockerfile
examples/mp-metrics-counted/README.adoc
examples/mp-metrics-counted/pom.xml

This adds Docker to the example.  It does not require the root user and the application is installed as the ROOT application.  It also corrects one of the URLs .

added Docker to mp metrics counted example

---

tomee/tomee-embedded/src/main/java/org/apache/tomee/embedded/Main.java

`supported commands: 'quit', 'exist'` -> `supported commands: 'quit', 'exit'`

embedded.Main#main: typo on 'exit'

---

docker-compose.yml

As an example to try out, improved docker-compose file.
This docker-compose.yml file runs as non-root user (some tests depend on this and fail if root).  To enable that there is a utility (volume_perms) that sets the file permissions to user 1000 which is the user id that runs the builds/tests.
Supported services:
(Fail on first failure)
docker-compose up build
(Build all regardless of failures)
docker-compose up build-all
(No tests)
docker-compose up build-quick
(Wait for debugger to connect. Usually want to specify -pl parameter first)
docker-compose up debug

Enhanced docker-compose.yml for non-root user build and debug

---

container/openejb-core/src/main/java/org/apache/openejb/BeanContext.java
container/openejb-core/src/main/java/org/apache/openejb/assembler/classic/Assembler.java
container/openejb-core/src/main/java/org/apache/openejb/cdi/CdiBuilder.java
container/openejb-core/src/main/java/org/apache/openejb/cdi/ThreadSingletonServiceImpl.java
container/openejb-core/src/main/java/org/apache/openejb/core/ThreadContext.java
container/openejb-core/src/main/java/org/apache/openejb/core/security/AbstractSecurityService.java
tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/TomcatLoader.java

Properly clear all registered thread context listeners that are not initialized as static instances.
Run all tests locally on Linux and Windows.
All pass.
Check https://issues.apache.org/jira/projects/TOMEE/issues/TOMEE-2454 for details.
- next is to re-enable EnvEntryTest from arquillian-tomee-jms-tests and see if that will break build on build bot.

Startup and shutdown fixes - TOMEE-2454

---

container/openejb-core/src/main/resources/default.exclusions
mp-jwt/src/main/java/org/apache/tomee/microprofile/jwt/cdi/MPJWTCDIExtension.java

Fixes JWT Filter being added in ALL cases even when tomee.mp.scan=none is set and fixes duplicate JWT Filter when tomee.mp.scan=all is set.

TOMEE-2408 Resolve MP JWT producer always being started or duplicated

---

examples/polling-parent/pom.xml
pom.xml

Slowness is fixed, so buildbot is happier but not quite happy.  Just for awareness to avoid someone else looking at it too...
1. I forgot to update the CXF version in the examples\polling-parent.  So polling-web failed.
2. Also, it turns out CXF didn't add support for mp rest client 1.2.0 until 3.3.0 either.
So I've updated those to dependency versions based on moving back to CXF 3.2.7 until that is fixed back up to 3.3.0.

Revert missed dependency versions

---

docs/deployments.adoc

This file is hosted at http://tomee.apache.org/deployments.html
Note there is still a broken link to "OPENEJB:Configuration", but I don't know where that should go (so it's not fixed by this PR)

Replace `openejb` references in deployments.adoc

---

examples/pom.xml
examples/webservice-ssl-client-cert/README.adoc
examples/webservice-ssl-client-cert/create-keystores.xml
examples/webservice-ssl-client-cert/keys/generateKeyPair.bat
examples/webservice-ssl-client-cert/keys/generateServerKey.bat
examples/webservice-ssl-client-cert/pom.xml
examples/webservice-ssl-client-cert/src/main/java/org/superbiz/calculator/CalculatorImpl.java
examples/webservice-ssl-client-cert/src/main/java/org/superbiz/calculator/CalculatorWs.java
examples/webservice-ssl-client-cert/src/main/resources/META-INF/ejb-jar.xml
examples/webservice-ssl-client-cert/src/main/resources/META-INF/openejb-jar.xml
examples/webservice-ssl-client-cert/src/test/conf/server.xml
examples/webservice-ssl-client-cert/src/test/java/org/superbiz/calculator/CalculatorTest.java
examples/webservice-ssl-client-cert/src/test/resources/META-INF/placeholder
examples/webservice-ssl-client-cert/src/test/resources/arquillian.xml

New example to show how to setup TomEE for HTTPS with SSL Client required.
In this example, we use JAX-WS as the example. Could be JAX-RS as well.

TOMEE-2525 Example for JAX-WS with SSL Client required

---

maven/jarstxt-maven-plugin/src/main/java/org/apache/openejb/maven/jarstxt/JarsTxtMojo.java

Fixes ISSUE [#TOMEE-2509](https://issues.apache.org/jira/browse/TOMEE-2509)
BufferedWriter can effectively reduce the times of IO access with caches, especially in a loop, which will be the performance bottleneck of program.

[TOMEE-2509] Wrap FileWriter with a BufferedWriter in a loop

---

container/openejb-core/src/test/java/org/apache/openejb/core/mdb/MaxSizePoolEndpointHandlerTest.java

Reduce the size of the pool to very small amount so that when test is run on high core CPU's it will not fail.

Extract some of the values in the test into constant definitions.

---

examples/deltaspike-configproperty/pom.xml
examples/deltaspike-exception-handling/pom.xml
examples/deltaspike-fullstack/pom.xml
examples/deltaspike-i18n/pom.xml

Updated DeltaSpike examples to use version 1.9.0 of DeltaSpike and enabled version to be read as a property for all DeltaSpike examples rather than defining the version number in the dependency itself.

TOMEE-2555 Brought DeltaSpike versions up to latest released version

---

examples/access-timeout/README_pt.adoc

Hey guys, there is my translation to examples/access-timeout.
I had enough difficulty with this example because some terms like "vendor", "bean", "container" and others, I don't know if it's lack of experience on my part but I see more this terms in english and its very difficult to translate literally. 
I did not want to dare to translate the specification into the part in which it is quoted so as not to run the risk of misinterpreting it.
I am totally open to suggestions for improvement.
Thank you !
Jira task: https://issues.apache.org/jira/browse/TOMEE-2534

TOMEE-2534 - Translate to Portuguese: examples/access-timeout.

---

server/openejb-cxf-rs/src/main/java/org/apache/openejb/server/cxf/rs/CxfRSService.java

This PR fixes a regression introduced with https://github.com/apache/tomee/commit/4302acab62bb64c2d77cce3a66b92ae7e9cff7c5 for TomEE 7.1.x with wrong values in the default CXF provider list. It was already fixed for TomEE 8 (see https://github.com/apache/tomee/commit/1bfb65a1837235f4e9ad4458f67aabcab5eff829), but was not backported to TomEE 7.1.x 
As described in the JIRA, affected end-users can workaround this issue by overriding the default list of providers using the `openejb.jaxrs.jsonProviders` system property witth the following value: 
```
"org.apache.openejb.server.cxf.rs.johnzon.TomEEJsonbProvider","org.apache.openejb.server.cxf.rs.johnzon.TomEEJsonpProvider"
```
Thanks to @cesarhernandezgt for showing me the magic of `git bisect` and finding the related commit in the first …

 [7.1.x] TOMEE-2565 - Fixes a regression with missing TomEEJsonbProvider in CXF Providers

---

container/openejb-core/src/main/java/org/apache/openejb/monitoring/ManagedMBean.java
container/openejb-core/src/main/java/org/apache/openejb/resource/activemq/ActiveMQ5Factory.java
container/openejb-core/src/main/java/org/apache/openejb/resource/activemq/jms2/JMSProducerImpl.java
mp-jwt/src/main/java/org/apache/tomee/microprofile/jwt/cdi/ClaimBean.java
server/openejb-common-cli/src/main/java/org/apache/openejb/server/cli/command/LocalJMXCommand.java

Hi,
this PR is a follow up of the discussion in https://github.com/apache/tomee/pull/427 and reflects the changes requested by @jgallimore 
I tied the changes to the lifecycle of the components using the `PropertyEditorRegistry` in each case.

TOMEE-2481 - Move code using PropertyEditors (deprecated class) to PropertyEditorRegistry

---

examples/webservice-ws-security/create-keystores.xml

Changed the keystore to be in JKS format so it works with both Java 8
and Java 11.

TOMEE-2586 Fix examples/webservices-ws-security to work on Java 11

---

examples/simple-mdb-with-descriptor/src/test/java/org/superbiz/mdbdesc/ChatBeanTest.java

Changed the package name of the test to correspond to the directory
structure.

TOMEE-1395 Invalid package on simple-mdb-with-descriptor

---

docs/jms-resources-and-mdb-container.adoc

This issue fixes the incorrect formatting for the table shown on:
http://tomee.apache.org/tomee-8.0/docs/jms-resources-and-mdb-container.html

Invalid Formatting on Jms Documentation.  Fixes TOMEE-2667

---

container/openejb-core/pom.xml
pom.xml
tomee/tomee-plume-webapp/pom.xml
tomee/tomee-plus-webapp/pom.xml

- Updates jackson-databind to 2.9.9.3 (was 2.9.6), see changelog https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9 (several CVEs are addressed)
- Updates `activemq` to 5.15.10
- Hint: In 7.1.x, "jackson-databind" is a transient dependency of "activemq-broker".
- https://issues.apache.org/jira/browse/TOMEE-2655
- https://www.cvedetails.com/vulnerability-list/vendor_id-15866/product_id-42991/Fasterxml-Jackson-databind.html

[TOMEE-2655] [7.1.x] Updates jackson-databind to 2.9.9.3 to mitigate CVE-2019-12384, CVE-2019-12814, CVE-2019-14379 and CVE-2019-14439

---

container/openejb-core/pom.xml
pom.xml
tomee/tomee-microprofile/mp-common/pom.xml

- Updates jackson-databind to 2.9.9.3 (was 2.9.4), see changelog https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9 (several CVEs are addressed)
- Updates activemq to 5.15.10 (also requires  jackson-databind in v 2.9.9.3)
- Hint: As micro-patches were applied (see changelog), the version number now differs from jackson-dataformat. Thus, a new version property was introduced.
- https://issues.apache.org/jira/browse/TOMEE-2655
- https://www.cvedetails.com/vulnerability-list/vendor_id-15866/product_id-42991/Fasterxml-Jackson-databind.html

[TOMEE-2655] Updates jackson-databind to 2.9.9.3 to mitigate CVE-2019-12384, CVE-2019-12814, CVE-2019-14379 and CVE-2019-14439

---

examples/mp-config-source-database/README_es.adoc

Add Spanish translation for:
https://github.com/apache/tomee/blob/master/examples/mp-config-source-database/README.adoc
Since the original readme.adoc was kind of incomplete, I've extended it in  #576  (TOMEE-2696)

TOMEE-2695 Add Spanish translation for mp-config-source-database

---

examples/mp-metrics-counted/README_es.adoc
examples/mp-metrics-gauge/README_es.adoc
examples/mp-metrics-histogram/README_es.adoc
examples/mp-metrics-metered/README_es.adoc
examples/mp-metrics-timed/README_es.adoc

Using proper English name:  **Microprofile** Instead of:  **Microperfil**

TOMEE-2694  - Unifying MicroProfile Spanish Translation

---

container/openejb-core/src/main/java/org/apache/openejb/core/security/AbstractSecurityService.java

Some tests in openejb-core fail, but it doen't seem related at all

TOMEE-2744: JD14 compatibility: remove usage of javax.security.acl

---

docs/documentation.adoc

I confirm that:
- Code compiles with JDK 8.
- adoc file produces a correct output with asciidoc.
- And, all tests pass successfully.
This is my first PR to the TomEE project. Please, give me your feedback to know what might I improve.  
More PRs are coming... :)

TOMEE-2767 / Deleting typos and correcting heading syntax

---

examples/vaadin-vxx-simple/README_es.adoc

https://issues.apache.org/jira/browse/TOMEE-2786
I noted that this example documentation emphasizes about using the latest vaadin release available, that currently are  alpha: `14.2.0.alpha6`  and stable versions: `14.1.18`  and  `15.0.0`
But the `pom.xml` file is using `14.0.0.rc1` updated about ~9 months ago by  commit 9fd13f96809
Would we update vaadin version for the examples as well at this time?
Ref: https://github.com/vaadin/platform/releases

TOMEE-2786 Spanish translation for vaadin-vxx-simple example

---

container/openejb-core/src/main/java/org/apache/openejb/cdi/OptimizedLoaderService.java
pom.xml
tck/microprofile-tck/openapi/src/test/resources/arquillian.xml
tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/TomcatWebAppBuilder.java
tomee/tomee-microprofile/mp-common/pom.xml
tomee/tomee-microprofile/mp-common/src/main/java/org/apache/tomee/microprofile/config/TomEEOpenAPIExtension.java
tomee/tomee-microprofile/mp-common/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension

This still has a single failing testcase in the OpenAPI TCK: 
```
[ERROR] Failures: 
[ERROR] org.eclipse.microprofile.openapi.tck.AirlinesAppTest.testRestClientNotPickedUp(org.eclipse.microprofile.openapi.tck.AirlinesAppTest)
[ERROR]   Run 1: AirlinesAppTest>Arquillian.run:164->testRestClientNotPickedUp:191 1 expectation failed.
JSON path paths.'/player/{playerId}' doesn't match.
Expected: null
Actual: {get={operationId=getPlayerById, responses={200={description=default response, content={application/json={schema={type=string}}}}, default={description=default response, content={application/json={schema={type=string}}}}}, parameters=[{schema={type=string}, in=path, name=playerId, style=simple, required=true}]}}
[ERROR]   Run 2: AirlinesAppTest>Arquillian.run:164->testRestClientNotPickedUp:1 …
```

TOMEE-2808 update to Johnzon 1.2.4

---

examples/jsonb-custom-serializer/README_pt.adoc

Linkt to Jira:  https://issues.apache.org/jira/browse/TOMEE-2824

TOMEE-2824-Translate to Portuguese: examples/jsonb-custom-serializer

---

docs/securing-a-web-service.adoc

On the Secure A Web Service page, there is a reference to an old OpenbEJB svn repo.  This has been modified to point to github.
There are also a few headers that are rendered incorrectly.  These have been resolved.
Fixes TOMEE-2860

Removed reference to svn

---

examples/simple-singleton/README_es.adoc

Translate into Spanish the README file using a suffix `_es` (simple-singleton/README.adoc into file simple-singleton/README_es.adoc). [TOMEE-2858](https://issues.apache.org/jira/browse/TOMEE-2858)

Translate to Spanish: example/simple-singlento  

---

container/openejb-core/src/test/java/org/apache/openejb/util/PropertiesTest.java

In the assertProperties() methodf, the logic for comparing when a property exists in both collections, but has a different value, the logic is incorrect and never fails.
I've changed the logic now so that it will fail as appropriate and catch any future errors.

Fix logic in assertProperties method. Fixes TOMEE-1417

---

examples/webservice-holder/README_pt.adoc
examples/webservice-ws-with-resources-config/README_pt.adoc

link to jira: https://issues.apache.org/jira/browse/TOMEE-2861

TOMEE-2861 Translate to Portuguese: examples/webservice-holder

---

examples/application-composer/README.adoc
examples/application-composer/README_pt.adoc

Link to jira: https://issues.apache.org/jira/browse/TOMEE-2903
Added new maven coordinates to the openejb-core artifact.

TOMEE-2903 - Application Composer Documentation has reference to old maven coordinates

---

examples/simple-ear/moviefun-functional-tests/pom.xml
examples/simple-ear/moviefun-functional-tests/src/test/java/org/superbiz/moviefun/DeployInWebAppsDirectoryTest.java
examples/simple-ear/moviefun-functional-tests/src/test/java/org/superbiz/moviefun/MoviesArquillianHtmlUnitTest.java

As discussed on the mailing list [3], we found test errors in `MoviesArquillianHtmlUnitTest`. 
While trying to reproduce it on my Linux machine, I found, that the dependencies used for setting up the unit tests do not match with the current project version. 
CI does not cover this as it can retrieve the old snapshot artifacts (either from local disk cache or from an apache snapshot repo).
With the version adjustments, the tests can be executed and do not throw the exception mentioned above
Question, @cesarhernandezgt : Can we run this PR on the CI environment to check, if the issue persists?
- [1] https://issues.apache.org/jira/browse/TOMEE-2930
- [2] https://ci-builds.apache.org/job/Tomee/job/tomee-7.0.x/org.superbiz$moviefun-functional-test/3/testReport/junit/org.superbiz.moviefun/Movies …

TOMEE-2930 - MoviesArquillianHtmlUnitTest -> Invalid byte 2 of 2-byte UTF-8 sequence. error.

---

examples/tomee-webprofile-embedded/src/test/java/org/superbiz/movie/MovieServiceTest.java

As discussed on the mailing list [1], we found test errors in `MovieServiceTest`. 
The root cause is, that the server only accepts `application/json` but the test was sending `text/xml` instead resulting in the exception in the PR's title.
I adjusted the test-case similar to the corresponding one on the [master](https://github.com/apache/tomee/blob/142f035e454b43192c51db7a66b9395982502d47/examples/serverless-tomee-webprofile/src/test/java/org/superbiz/movie/wp/MovieServiceTest.java) branch.
- [1] https://openejb.markmail.org/search/?q=type:development#query:type%3Adevelopment+page:1+mid:yagkenymmvojwqvh+state:results
- [2] https://issues.apache.org/jira/browse/TOMEE-2932

TOMEE-2932 - Fixes javax.ws.rs.NotSupportedException: HTTP 415 Unsupported Media Type

---

boms/tomee-microprofile/pom.xml
boms/tomee-plume/pom.xml
boms/tomee-plus/pom.xml
boms/tomee-webprofile/pom.xml
deps/pom.xml
deps/taglibs-shade/pom.xml
pom.xml
tck/cdi-embedded/pom.xml
tomee/tomee-embedded/pom.xml
tomee/tomee-webapp/pom.xml

This should allow the Taglibs library to use the XPath API part of Xalan that it is tightly coupled to, but allow applications to use JAXP provided by the JDK.

Experimental change to shade taglibs, xalan and serializer

---

pom.xml

Jenkins build for the "master-owasp-check" failed due to an unresolveable maven property `maven.multiModuleProjectDirectory` [1]. This property is indeed for internal use only as it is undocumented.
This PR moves the configuration of the `suppressionFile` to the `pluginManagement` section as suggested in the related project issue [2]. I did a run locally, which worked fine. I guess, that this should also work fine on the asf jenkins.
_Note: Cannot merge it myself yet due to missing write permissions._
[1] https://ci-builds.apache.org/job/Tomee/job/master-owasp-check/20/console
[2] https://github.com/jeremylong/DependencyCheck/issues/2152

TOMEE-2957 - Fix OWASP Checks on ASF Jenkins Environment

---

container/openejb-core/src/main/java/org/apache/openejb/resource/jdbc/DataSourceFactory.java
tomee/tomee-jdbc/src/test/java/org/apache/tomee/jdbc/TomcatDataSourceConfigurationTest.java

-  custom configured `MaxWait`, `TimeBetweenEvictionRunsMillis` and `MinEvictableIdleTimeMillis` properties for a datasource are **not** ignored when `TomEEDataSourceCreator` is used.
- adds a unit test to reproduce the behaviour described in TOMEE-2125 (also affects 7.0.x, 7.1.x and 8.0.x - we might need to backport it)
- https://issues.apache.org/jira/browse/TOMEE-2125
- https://www.mail-archive.com/users@tomee.apache.org/msg17591.html

TOMEE-2125: Datasource Config: MaxWait, TimeBetweenEvictionRunsMillis and MinEvictableIdleTimeMillis are ignored

---

container/openejb-core/src/main/java/org/apache/openejb/classloader/ProvisioningClassLoaderConfigurer.java
container/openejb-core/src/main/java/org/apache/openejb/util/PropertyPlaceHolderHelper.java
container/openejb-core/src/test/java/org/apache/openejb/util/PropertyPlaceHolderTest.java
tomee/tomee-jdbc/src/test/java/org/apache/tomee/jdbc/TomcatDataSourceConfigurationTest.java

- Adds unit tests to reproduce TOMEE-2968 (also affects 7.0.x and 7.1.x)
- Single opening curly braces are stripped away in property values as we treat them as suffix placeholders (even in the case, we did not have an opening curly brace). PR proposes a related fix.
- https://issues.apache.org/jira/browse/TOMEE-2968
- https://markmail.org/message/vxmm7t5sl33zr4wq

TOMEE-2968: Postgres connection error when a password contains "}"

---

pom.xml

Jenkins environment fails with `TomEEJsonbProviderTest` due to encoding issues. This tests uses a German locale to format a date. As we are in March now, it uses a German umlaut, which is wrongly encoded. 
- Enforces `-Dfile.encoding=UTF-8` for surefire executed tests.
- My Ubuntu machine uses a default locale of de_DE and a default encoding of UTF-8. Testing the change via **PR Jenkins builder** (which also uses ISO-8859-1 with en_US locale)
- https://issues.apache.org/jira/browse/TOMEE-2974
- http://mail-archives.apache.org/mod_mbox/tomee-dev/202103.mbox/%3C5c21f88fae20d7fd59d8959171d0f9b529b2fb20.camel%40hs-heilbronn.de%3E

TOMEE-2974 - Set file.encoding=UTF-8 for tests executed via surefire

---

examples/reload-persistence-unit-properties/README_pt.adoc

link to jira: https://issues.apache.org/jira/browse/TOMEE-2890

TOMEE-2890 Translate to Portuguese: examples/reload-persistence-unit

---

tomee/tomee-common/src/main/resources/conf/web.xml
tomee/tomee-embedded/src/main/resources/org/apache/tomee/configs/web.xml

- Updates `web.xml` to current Tomcat's version (v9.0.45)  to honor missing mime types and other changes since 2011
- Jasper should run in production mode (TomEE modification compared to Tomcat version)

TOMEE-3718 - Aligns with Tomcat's web.xml due to missing mime type mapping

---

examples/rest-cdi/README.adoc

For comparison check last tests block https://github.com/Dexmaster/tomee/blob/master/examples/rest-cdi/README.adoc vs https://github.com/apache/tomee/blob/master/examples/rest-cdi/README.adoc

Fix example adoc typo

---

examples/javamail-velocity/README.adoc
examples/javamail-velocity/pom.xml
examples/javamail-velocity/src/main/java/org/superbiz/EMail.java
examples/javamail-velocity/src/main/java/org/superbiz/EMailServiceImpl.java
examples/javamail-velocity/src/main/java/org/superbiz/MailType.java
examples/javamail-velocity/src/main/resources/resources.xml.template
examples/javamail-velocity/src/test/java/org/superbiz/EMailServiceTest.java
examples/javamail-velocity/src/test/resources/log4j.xml
examples/javamail-velocity/src/test/resources/templates/email-html-template.vm
examples/pom.xml

- This examples demonstrates the use of the Javamail API in combination with https://velocity.apache.org to create templated HTML Emails.
- It mentioned the new properties from Geronimo Javamail 1.6 introduced with `1.0.1`, which allow the specification of the `cipersuites` and `protocols` used for TLS/SSL security.

TOMEE-3811 - Provide E-Mail Example with Velocity

---

docs/tomee-maven-plugin.adoc

Inline quoted text seems to have been lost in the conversion from MD to adoc.   For unknown reasons it's missing on the web page but visible in view-source for https://tomee.apache.org/tomee-maven-plugin.html, which makes me wonder if this is really the source file or if the web page hasn't been redeployed since the conversion.

Restore missing Inline quoted text for tomee-maven-plugin.adoc

---

tomee/tomee-microprofile/mp-common/pom.xml

-  Use patched cxf-shade to ensure TomEEJson(b|p)Provider are registered in tomee-embedded-maven-plugin when MicroProfile is present
- https://issues.apache.org/jira/browse/TOMEE-3832

TOMEE-3832 - JAX-RS TomEEJsonbProvider not registered in tomee-embedded-maven-plugin when MicroProfile is present

---

tomee/apache-tomee/src/test/java/org/apache/tomee/bootstrap/GenerateBoms.java

now group and artifact ids have dots instead of slashes. now ok under windows like its was already ok on linux and mac

TOMEE-3876 - Fixed BOM generation under windows

---

docs/comparison.adoc
docs/documentation.adoc
docs/documentation.old.adoc

this is the "per-version" comparison page for v9

TOMEE-3846 Add Comparison page for TomEE v9 master

---

itests/tomee-server-version/pom.xml

Hi! I found the pom file of project **_org.apache.tomee:tomee-server-version:9.0.0-M8-SNAPSHOT_** introduced **_6_** dependencies. However, among them, **_3_** libraries (**_50%_**) are not used by your project. I list the redundant dependencies below (labelled as red ones in the figure):
org.tomitribe:tomitribe-util:jar:1.2.3:compile
org.tomitribe:swizzle:jar:1.0:compile
org.apache.commons:commons-compress:jar:1.14:compile
---
Removing the redundant dependencies can reduce the size of project and prevent potential dependency conflict issues (i.e., multiple versions of the same library). More importantly, one of the redundant dependencies **_org.apache.commons:commons-compress:jar:1.14:compile_** incorporates a medium-level vulnerability SNYK-JAVA-ORGAPACHECOMMONS-1316639. As such, I …

Could org.apache.tomee:tomee-server-version:9.0.0-M8-SNAPSHOT drop off redundant dependencies?

---

container/openejb-core/src/main/java/org/apache/openejb/cdi/CdiEjbBean.java

I don't actually know what a `MDB` is, after a quick google i'm guessing it a `MessageDriven` bean".  Either way, the error message should spell it out.
> **NOTE:** I updated this through GitHub's web view, if CI fails, and this change is _valid_ I'll try to fix the patch.

Update exception message for MDB without an interface

---

.gitignore
tomee/apache-tomee/pom.xml
tomee/apache-tomee/src/template/patch/java/org/apache/catalina/util/ServerInfo.properties
tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/ServerListener.java

- Avoid reflectional access to modify ServerInfo in Tomcat, which doesn't work in Java 17 anymore
- Use the patch plugin to provide a patched ServerInfo.properties which is bootstrapped during the TomEE build process

TOMEE-4014 - Unable to see TomEE version in Tomcat home page with Java 17

---

docs/comparison.adoc

Tomcat does not include JSTL nor the javax.security.enterprise.* packages.
The documentation should reflect that, and should have these specs into WebProfile.

TOMEE-4023 Comparison pages with wrong specs per profile

---

arquillian/arquillian-tomee-tests/arquillian-tomee-webprofile-tests/src/test/resources/hibernate-pom.xml
arquillian/arquillian-tomee-tests/pom.xml
boms/tomee-microprofile/pom.xml
boms/tomee-plume/pom.xml
boms/tomee-plus/pom.xml
examples/jpa-eclipselink/pom.xml
examples/multi-jpa-provider-testing/src/test/resources/hibernate-pom.xml
examples/mvc-cxf-hibernate/pom.xml
examples/mvc-cxf/pom.xml
examples/tomee-jersey-eclipselink/pom.xml
pom.xml
utils/openejb-core-hibernate/pom.xml

versions of SmallRye that were RC are now stable releases.
hibernate 6.0 is EOL, use 6.1 instead (compatible jakarta 9.1).
updated mojarra (faces) to 3.0.2 eclipselink to 3.0.3 krazo (mvc) to 2.0.2

[TOMEE-4035] Upgrade dependencies (SmallRye, Jackson, ...)

---

container/openejb-core/pom.xml
examples/alternate-descriptors/pom.xml
examples/multi-jpa-provider-testing/pom.xml
examples/rest-example/pom.xml
examples/tomee-jersey-eclipselink/pom.xml
examples/xa-datasource/pom.xml
pom.xml

Updates : 
- [TOMEE-4060](https://issues.apache.org/jira/browse/TOMEE-4064) Tomcat 9.0.67
- [TOMEE-4064](https://issues.apache.org/jira/browse/TOMEE-4064) OpenJPA 3.2.2 (examples)
- [TOMEE-4064](https://issues.apache.org/jira/browse/TOMEE-4064) EclipseLink 2.7.11 (examples)
- [TOMEE-4064](https://issues.apache.org/jira/browse/TOMEE-4064) Derby 10.14.2.0
- [TOMEE-4062](https://issues.apache.org/jira/browse/TOMEE-4062) Apache BVal 2.0.6
- [TOMEE-4063](https://issues.apache.org/jira/browse/TOMEE-4063) Geronimo Transcation Manager 3.1.5

[TOMEE-4060] Tomcat 9.0.67 and dependencies update

---

boms/tomee-microprofile/pom.xml
boms/tomee-plume/pom.xml
boms/tomee-plus/pom.xml
pom.xml

TomEE 8.x dependencies update:
* [TOMEE-4086](https://issues.apache.org/jira/browse/TOMEE-4086) HSQLDB 2.7.1
* [TOMEE-4094](https://issues.apache.org/jira/browse/TOMEE-4094) jackson 2.14.0-rc2

[TOMEE-4092] TomEE 8.x dependencies update: hsqldb 2.7.1 and jackson update

---

arquillian/arquillian-tomee-remote/pom.xml
arquillian/arquillian-tomee-tests/arquillian-tomee-webprofile-tests/pom.xml
arquillian/arquillian-tomee-tests/arquillian-tomee-webprofile-tests/src/test/resources/hibernate-pom.xml
boms/tomee-microprofile/pom.xml
boms/tomee-plume/pom.xml
boms/tomee-plus/pom.xml
boms/tomee-webprofile/pom.xml
container/openejb-core/pom.xml
examples/multi-jpa-provider-testing/src/test/resources/hibernate-pom.xml
examples/mvc-cxf-hibernate/pom.xml
examples/websocket-tls-basic-auth/pom.xml
examples/xa-datasource/pom.xml
itests/openejb-itests-beans/pom.xml
maven/tomee-webapp-archetype/pom.xml
pom.xml
tomee/tomee-plume-webapp/pom.xml
tomee/tomee-plus-webapp/pom.xml
tomee/tomee-webapp/pom.xml

TomEE 9.x dependencies update: 
- [TOMEE-4096](https://issues.apache.org/jira/browse/TOMEE-4096) Tomcat 10.0.27
- [TOMEE-4086](https://issues.apache.org/jira/browse/TOMEE-4086) HSQLDB 2.7.1
- [TOMEE-4095](https://issues.apache.org/jira/browse/TOMEE-4095) jackson databind 2.13.4.2
- Derby 10.14.2.0
- [TOMEE-4093](https://issues.apache.org/jira/browse/TOMEE-4093) Hibernate 6.1.4.Final
- [TOMEE-4097](https://issues.apache.org/jira/browse/TOMEE-4097) MicroProfile Fault Tolerance API 4.0.2
- [TOMEE-4098](https://issues.apache.org/jira/browse/TOMEE-4098) MicroProfile Health API 4.0.1
- [TOMEE-4099](https://issues.apache.org/jira/browse/TOMEE-4099) MicroProfile Rest Client API 3.0.1

[TOMEE-4061] TomEE 9.x dependencies update: hsqldb 2.7.1, jackson, etc. - MERGE FIRST

---

itests/pom.xml
itests/tomee-security-itests/pom.xml
itests/tomee-security-itests/src/test/java/org/apache/tomee/security/itest/AnotherAuthMechanism.java
itests/tomee-security-itests/src/test/java/org/apache/tomee/security/itest/AuthMechanism.java
itests/tomee-security-itests/src/test/java/org/apache/tomee/security/itest/LoginToContinueTest.java
tomee/tomee-security/src/main/java/org/apache/tomee/security/cdi/BasicAuthenticationMechanism.java
tomee/tomee-security/src/main/java/org/apache/tomee/security/cdi/LoginToContinueInterceptor.java
tomee/tomee-security/src/main/java/org/apache/tomee/security/cdi/TomEESecurityServletAuthenticationMechanismMapper.java

instead of requiring the interface to be implemented. Thanks Stefan Kalscheuer for reporting and for the fix

TOMEE-4065 Fix to allow @LoginToContinue to be used directly in the HttpAuthenticationMechanism

---

mp-jwt/src/main/java/org/apache/tomee/microprofile/jwt/jaxrs/MPJWPProviderRegistration.java
server/openejb-rest/src/main/java/org/apache/openejb/server/rest/RESTService.java
tck/microprofile-tck/opentracing/src/test/java/org.apache.tomee.microprofile.tck.opentracing/MicroProfileOpenTracingTCKDeploymentPackager.java
tck/microprofile-tck/opentracing/src/test/resources/META-INF/services/jakarta.ws.rs.ext.Providers
tomee/tomee-microprofile/mp-common/pom.xml
tomee/tomee-microprofile/mp-common/src/main/java/org/apache/tomee/microprofile/TomEEMicroProfileListener.java
tomee/tomee-microprofile/mp-common/src/main/java/org/apache/tomee/microprofile/opentracing/MicroProfileOpenTracingExceptionMapper.java

Register OpenTracing providers during MP initialization

Make sure providers aren't scanned if Application returns classes or singletons.

---

tomee/apache-tomee/src/patch/java/org/apache/catalina/util/ServerInfo.java
tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/ServerListener.java

TOMEE-4014 - Re-add "tomee.keep-server-info"

---

server/openejb-client/src/main/java/org/apache/openejb/client/EJBInvocationHandler.java
server/openejb-client/src/main/java/org/apache/openejb/client/EntityEJBHomeHandler.java

Fix for memory link in bmp entity finder registration (JIRA TOMEE-4120)
Also eliminated double registration of the same handler

TOMEE-4120

---

deps/cxf-rt-rs-mp-client-shade/pom.xml
examples/mp-config-example/pom.xml
examples/mp-custom-healthcheck/pom.xml
examples/mp-faulttolerance-fallback/pom.xml
examples/mp-faulttolerance-retry/pom.xml
examples/mp-faulttolerance-timeout/pom.xml
examples/mp-metrics-counted/pom.xml
examples/mp-metrics-gauge/pom.xml
examples/mp-metrics-histogram/pom.xml
examples/mp-metrics-metered/pom.xml
examples/mp-metrics-timed/pom.xml
examples/mp-rest-client/README.adoc
examples/mp-rest-client/README_es.adoc
examples/mp-rest-client/README_pt.adoc
examples/mp-rest-client/pom.xml
itests/microprofile-jwt-itests/pom.xml
itests/tomee-microprofile-itests/pom.xml
mp-jwt/pom.xml
pom.xml
tck/microprofile-tck/config/pom.xml
tck/microprofile-tck/fault-tolerance/pom.xml
tck/microprofile-tck/health/pom.xml
tck/microprofile-tck/jwt/pom.xml
tck/microprofile-tck/metrics/pom.xml
tck/microprofile-tck/openapi/pom.xml
tck/microprofile-tck/opentracing/pom.xml
tck/microprofile-tck/pom.xml
tck/microprofile-tck/rest-client/pom.xml
tomee/tomee-microprofile/mp-common/pom.xml

this one is about tck tests and microprofile api & impl.
thanks @jeanouii for the wss4j merge
some of our TCK modules depend directly on smallrye impl. is it intendend ?
* JWT TCK
* OpenTracing TCK

[TOMEE-4053] Dependency properties cleanup, step 3 on branch 9.x

---

arquillian/arquillian-tomee-remote/pom.xml
container/openejb-core/src/test/java/org/apache/openejb/resource/jdbc/driver/AlternateDriverJarTest.java
examples/xa-datasource/pom.xml
pom.xml

This is a tentative to update Derby to 10.15.x, upon other dep updates.
Derby 10.15.x is modular, it might break CI, please merge wisely.
TO BE MERGED AFTER: 
* PR #938 
* PR #953 
TomEE 9.x dependencies update: 
- Derby 10.15.2.0

[TOMEE-4061] TomEE 9.x + Derby 10.15.2.0, upon other dependencies update

---

examples/mp-config-example/pom.xml
examples/mp-custom-healthcheck/pom.xml
examples/mp-faulttolerance-fallback/pom.xml
examples/mp-faulttolerance-retry/pom.xml
examples/mp-faulttolerance-timeout/pom.xml
examples/mp-metrics-counted/pom.xml
examples/mp-metrics-gauge/pom.xml
examples/mp-metrics-histogram/pom.xml
examples/mp-metrics-metered/pom.xml
examples/mp-metrics-timed/pom.xml
examples/mp-rest-client/pom.xml
pom.xml

Edited:
This PR needs to be merged *AFTER* PR #997
* PR #997 
[TOMEE-4140] Update Micro Profile from 5.0 to 6.0 : 
* update MP Config from 3.0.1 to 3.0.2
* update MP Health from 4.0 to 4.0.1
* update MP JWT from 3.0 to 3.1
* update MP Metrics from 3.0.1/4.0.1 to 5.0.0
* update MP Open API from 3.0 to 3.1
* update MP Rest from 3.0 to 3.0.1
* update Small Rye except the Metrics stays at 4.0.0 (instead of updating to 5.0.0)
Small Rye Metrics 5.0.0 to be done in another PR
I cant run the TCKs at the moment.
The TCKs might not pass after this PR.
It is precisely intended to detect the failing TCKs.

[TOMEE-4140] Update Micro Profile to 6.0 except SmallRye Metrics

---

pom.xml

this PR removes some unused properties.
please build against CI and/or TCK to ensure these properties arent used by some shadowy mechanism
some of these properties *could* be used on existing dependencies but this will be done in another PR
<geronimo-osgi.version>1.1</geronimo-osgi.version>
<org.apache.axis2.version>1.4.1</org.apache.axis2.version>
<pax-url.version>1.3.5</pax-url.version>
<plexus.version>1.5.5</plexus.version>
<plexus-utils.version>3.0.10</plexus-utils.version>
<scannotation.version>1.0.2</scannotation.version>
<wagon.version>2.2</wagon.version>

[TOMEE-4053] Dependency properties cleanup, branch 8.x

---

tomee/tomee-common/src/main/java/org/apache/tomee/installer/Installer.java

The classpath for the `version` command of  `./catalina[.sh|.bat] ` does only contain
```bash
-classpath "$CATALINA_HOME/lib/catalina.jar"  org.apache.catalina.util.ServerInfo
```
Thus, our reflection code introduced with https://github.com/apache/tomee/commit/7ce518e29111ba10cd6bcf5a8fc613fc912b84a8 and https://github.com/apache/tomee/commit/14a034cc9528247d2c30c052412e730d64dea094 will fail with a `ClassNotFoundException` as `openejb-core` isn't available in the given classpath.
However, this is the only occurence within  `./catalina[.sh|.bat] ` , so it should be ok to adjust the classpath for the given command only.

TOMEE-4189 - java.lang.ClassNotFoundException: org.apache.openejb.loader.SystemInstance

---

container/openejb-core/src/main/java/org/apache/openejb/testing/ApplicationComposers.java
container/openejb-junit5/src/test/java/org/apache/openejb/junit5/AppComposerMemoryReleaseTest.java

Ported from https://github.com/apache/tomee/pull/1030

TOMEE-4192 - ApplicationComposers do not clear GC references on release

---

boms/tomee-microprofile/pom.xml
boms/tomee-plume/pom.xml
boms/tomee-plus/pom.xml
boms/tomee-webprofile/pom.xml
server/openejb-client/pom.xml
server/openejb-cxf/pom.xml
tomee/tomee-embedded/pom.xml

- Upgrades bouncycastle libs to 1.73
- Fixes mess regarding different versions of the same lib within `/lib`.
CI Full Build: https://ci-builds.apache.org/job/Tomee/job/pull-request-9.x-manual/9/

TOMEE-4204 - Upgrade Bouncycastle to 1.73

---

tomee/tomee-security/src/main/java/org/apache/tomee/security/http/SavedAuthentication.java
tomee/tomee-security/src/main/java/org/apache/tomee/security/http/SavedRequest.java
tomee/tomee-security/src/test/java/org/apache/tomee/security/http/SavedAuthenticationTest.java
tomee/tomee-security/src/test/java/org/apache/tomee/security/http/SavedRequestTest.java

(cherry picked from commit 4d9f032368d4cac936ed40c1ad7771ca4021b8b6)

[tomee-9.x] Fix TOMEE-4222 - LoginToContinue causes IllegalArgumentException: setAttribute: Non-serializable attribute

---

container/openejb-core/src/main/java/org/apache/openejb/monitoring/DynamicMBeanWrapper.java

which should fall back to `arg0`-like syntax, if debug information was not compiled in

Close Tomee-4031 - JMX should attempt to use parameter names from reflection

---

container/openejb-core/src/main/java/org/apache/openejb/monitoring/DynamicMBeanWrapper.java

which should fall back to arg0 syntax if information was not compiled in
(cherry picked from commit ea068b4e633e81ef730493521fe610ac7e801004)

[tomee-8] Close Tomee-4031 - JMX should attempt to use parameter names from reflection

---

container/openejb-core/src/main/java/org/apache/openejb/config/AnnotationDeployer.java
container/openejb-core/src/main/java/org/apache/openejb/config/AutoConfig.java
container/openejb-core/src/main/java/org/apache/openejb/config/event/DataSourceDefinitionUrlBuild.java
container/openejb-core/src/test/java/org/apache/openejb/assembler/classic/DataSourceDefinitionUrlBuildTest.java

- Check for modern PostgreSQL driver, if JDBCUrl is not specified in @DataSourceDefinition
- Fixes TOMEE-4226: https://issues.apache.org/jira/browse/TOMEE-4226
- Introduces `DataSourceDefinitionUrlBuild` to "plugin" custom `@Event` listener to adjust datasource definition, if needed.

TOMEE-4226 - Check for modern PostgreSQL driver, if JDBCUrl is not specified in @DataSourceDefinition

---

pom.xml

Close #TOMEE-4263: Update Apache Santuario to 2.3.4 from 2.3.2 (xmlsec) to mitigate CVE-2023-4448

Close #TOMEE-4263: Update Apache Santuario to 2.3.4 from 2.3.2 (xmlsec) to mitigate CVE-2023-4448

---

container/openejb-core/src/main/java/org/apache/openejb/core/BaseContext.java

The `EJBContext` methods `getEnvironment`, `getCallerIdentity` and `isCallerInRole(Identity)` were removed in Jakarta EE 9, but their implementations remain in `BaseContext`.
This PR suggests we remove these now-obsolete methods and also add `@Override` annotations to prevent future removals going unnoticed.
This also removed the depdency on the deprecated for-removal `java.security.Identity` class and allows TomEE to run on future JREs where this class has been removed.

Remove obsolete EJBContext methods 

---

boms/tomee-plume/pom.xml
pom.xml

Upgraded EclipseLink Dependency to 3.0.4 (support for Java 21-compiled code)

Tomee 4291 EclipseLink 3.0.4 Dependency Upgrade

---

tomee/tomee-microprofile/mp-common/pom.xml

Fixed exclusions (related to TOMEE-4294)
otherwise you have a duplicate CDI classes on classpath when running with tomee embedded maven plugin

Fixed exclusions (related to TOMEE-4294)

---

container/openejb-core/src/main/java/org/apache/openejb/cdi/WebAppElResolver.java
container/openejb-core/src/main/java/org/apache/openejb/resource/thread/ManagedScheduledExecutorServiceImplFactory.java
container/openejb-core/src/main/java/org/apache/openejb/threads/task/CUTask.java
container/openejb-jee/src/main/java/org/apache/openejb/jee/Application.java
pom.xml

- removed deprecated EL method override
- fallback to a default ContextService in ManagedScheduledExecutorServiceImpl
- removed unused var in CUTask
- removed not-existing jetty dependency

Concurrency work

---

itests/openejb-itests-optional-classes/3rdpartydep/pom.xml
itests/openejb-itests-optional-classes/3rdpartydep/src/main/java/org/apache/tomee/itests/optional/thirdparty/ThirdPartyApi.java
itests/openejb-itests-optional-classes/3rdpartydep/src/main/resources/META-INF/beans.xml
itests/openejb-itests-optional-classes/app/pom.xml
itests/openejb-itests-optional-classes/app/src/main/resources/META-INF/beans.xml
itests/openejb-itests-optional-classes/app/src/test/java/org/apache/tomee/itests/optional/app/OptionalDependencyResolutionTest.java
itests/openejb-itests-optional-classes/lib_with_optional_dep/pom.xml
itests/openejb-itests-optional-classes/lib_with_optional_dep/src/main/java/org/apache/tomee/itests/optional/optlib/Bicycle.java
itests/openejb-itests-optional-classes/lib_with_optional_dep/src/main/java/org/apache/tomee/itests/optional/optlib/Car.java
itests/openejb-itests-optional-classes/lib_with_optional_dep/src/main/java/org/apache/tomee/itests/optional/optlib/SomeBean.java
itests/openejb-itests-optional-classes/lib_with_optional_dep/src/main/java/org/apache/tomee/itests/optional/optlib/Vehicle.java
itests/openejb-itests-optional-classes/lib_with_optional_dep/src/main/resources/META-INF/beans.xml
itests/openejb-itests-optional-classes/pom.xml

if a class creates a NoClassDefFoundError or ClassNotFoundException then it's simply not an eligible bean class.
All works fine in TomEE 10!

add an integration test for optional beans

---

tomee/tomee-microprofile/mp-common/src/main/java/org/apache/tomee/microprofile/TomEEMicroProfileListener.java

Fixes [TOMEE-4295](https://issues.apache.org/jira/browse/TOMEE-4295)

[TOMEE-4295] load mp-common via codesource

---

itests/microprofile-jwt-itests/src/test/java/org/apache/tomee/microprofile/jwt/itest/AllowNoExpPropertyTest.java
mp-jwt/src/main/java/org/apache/tomee/microprofile/jwt/config/JWTAuthConfiguration.java
mp-jwt/src/main/java/org/apache/tomee/microprofile/jwt/config/JWTAuthConfigurationProperties.java

TOMEE-4297 fixing two failed tests

---

tomee/tomee-microprofile/mp-common/src/main/java/org/apache/tomee/microprofile/TomEEMicroProfileListener.java

Add a Jandex index cache to TomEEMicroProfileListener
This will fix a issue with a longer startup time since TomEE 9
The processApplication method is called for every created application and will then create an index for all jars.
But the index is based on the AppInfo of the application. The AppInfo can have multiple applications.
So currently the same index is created for every single application which is unnecessary
This change will boost our start up time from 2min to ~45s

TOMEE-4357 - Add Jandex Index cache - 9.x

---

container/openejb-core/src/test/java/org/apache/openejb/core/asynch/AsyncInnerClassTest.java
container/openejb-jee/src/main/java/org/apache/openejb/jee/AsyncMethod.java

if loading a class that is a parameter to an Async method fails with java.lang.ClassNotFoundException replace last '.' with '$' and retry in hope that it is an inner class, else throw original exception.
The method params comes with '.' for inner classes from here
`
org.apache.openejb.jee.AsyncMethod(final java.lang.reflect.Method method)
`

#TOMEE-2934 if loading a class that is a parameter to an Async method

---

tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/HttpServletRequestProxy.java
tomee/tomee-catalina/src/main/java/org/apache/tomee/catalina/RequestNotActiveException.java
tomee/tomee-catalina/src/test/java/org/apache/tomee/catalina/HttpServletRequestProxyTest.java

As the title says, see https://issues.apache.org/jira/browse/TOMEE-4410

TOMEE-4410 - Better Exception when accesing injected HttpServletRequest if no request is active

---

arquillian/arquillian-tomee-tests/arquillian-tomee-jaxrs-tests/src/test/java/org/apache/openejb/arquillian/tests/jaxrs/faces/AvoidConflictWithFacesTest.java
arquillian/arquillian-tomee-tests/arquillian-tomee-jaxrs-tests/src/test/java/org/apache/openejb/arquillian/tests/jaxrs/faces/MyRestApi.java
arquillian/arquillian-tomee-tests/arquillian-tomee-jaxrs-tests/src/test/java/org/apache/openejb/arquillian/tests/jaxrs/faces/MyRestApplication.java
server/openejb-cxf-rs/src/main/java/org/apache/openejb/server/cxf/rs/CxfRsHttpListener.java
tomee/tomee-jaxrs/src/main/java/org/apache/tomee/webservices/CXFJAXRSFilter.java
tomee/tomee-jaxrs/src/main/java/org/apache/tomee/webservices/TomcatRsRegistry.java

See https://issues.apache.org/jira/browse/TOMEE-4406
Full build: https://ci-builds.apache.org/job/Tomee/view/tomee-10.x/job/pull-request-manual/139/
With this change registered servlets (e.g. via web.xml, @WebServlet or a ServletContextListener) take precedence over possible JAX-RS endpoints

TOMEE-4406 - Improved request matching in CXFJAXRSFilter

---

examples/mp-custom-healthcheck/src/test/java/org/superbiz/test/WeatherServiceTest.java
examples/mp-rest-jwt-public-key/src/test/java/org/superbiz/bookstore/BookstoreTest.java
server/openejb-cxf-rs/src/main/java/org/apache/openejb/server/cxf/rs/CxfRSService.java
tck/jax-rs/jax-rs-tests-embedded/pom.xml
tck/jax-rs/jax-rs-tests/pom.xml

Adjust TomEE to latest CXF JAX-RS 3.1 related changes which are failing the build, cf. https://github.com/apache/cxf/commit/b6d1e6978bdea139d6d093656f92979b7d6cb204 for CXF details
- https://ci-builds.apache.org/job/Tomee/view/tomee-10.x/job/pull-request-manual/152/
- JAX-RS TCK -> ok

Disable JSON-P / JSON-B Default Registration in JAX-RS 3.1 (from CXF 4.1.0-SNAPSHOT)

---

arquillian/arquillian-tomee-tests/arquillian-tomee-jaxrs-tests/src/test/java/org/apache/openejb/arquillian/tests/jaxrs/servlets/welcomefile/MyFiletypeServlet.java
arquillian/arquillian-tomee-tests/arquillian-tomee-jaxrs-tests/src/test/java/org/apache/openejb/arquillian/tests/jaxrs/servlets/welcomefile/MyRestApi.java
arquillian/arquillian-tomee-tests/arquillian-tomee-jaxrs-tests/src/test/java/org/apache/openejb/arquillian/tests/jaxrs/servlets/welcomefile/MyRestApplication.java
arquillian/arquillian-tomee-tests/arquillian-tomee-jaxrs-tests/src/test/java/org/apache/openejb/arquillian/tests/jaxrs/servlets/welcomefile/ServletsWithWelcomeFileTest.java
tomee/tomee-jaxrs/src/main/java/org/apache/tomee/webservices/CXFJAXRSFilter.java

See https://issues.apache.org/jira/browse/TOMEE-4424
Fulll build is running: https://ci-builds.apache.org/job/Tomee/view/tomee-10.x/job/pull-request-manual/146/

TOMEE-4424 - improved JAX-RS request matching if a welcome-file is defined

---

boms/tomee-microprofile/pom.xml
boms/tomee-plume/pom.xml
boms/tomee-plus/pom.xml
boms/tomee-webprofile/pom.xml
tomee/apache-tomee/src/test/java/org/apache/tomee/bootstrap/GenerateBoms.java

The tomee-webapps are no longer deployed to a remote Maven repository, see https://issues.apache.org/jira/browse/TOMEE-3724
As a result, their artifacts should be excluded from the BOM generation process to prevent missing dependencies. Currently, the 10.0.0-GA BOMS are unusable.
This PR updates the BOM generation logic to filter out web app artifacts, ensuring that only valid, published artifacts are included.

TOMEE-4454 - Missing artifacts in BOM generated files due to webapp removal

---

container/openejb-core/src/main/java/org/apache/openejb/assembler/classic/BeansInfo.java
container/openejb-core/src/main/java/org/apache/openejb/cdi/CompositeBeans.java
container/openejb-core/src/main/java/org/apache/openejb/config/EjbJarInfoBuilder.java
itests/trimmedBeans/src/main/java/org/apache/tomee/itests/trimmedbeans/BeanA.java
itests/trimmedBeans/src/main/java/org/apache/tomee/itests/trimmedbeans/BeanB.java
itests/trimmedBeans/src/main/java/org/apache/tomee/itests/trimmedbeans/NotPickedUpBean.java
itests/trimmedBeans/src/main/resources/META-INF/beans.xml
itests/trimmedBeans/src/test/java/org/apache/tomee/itests/trimmedbeans/TrimmedBeansTest.java

plz review. Will commit after review.

TOMEE-4456 add <trim/> support for embedded use case

---

container/openejb-core/src/main/java/org/apache/openejb/core/security/AbstractSecurityService.java
container/openejb-core/src/main/java/org/apache/openejb/core/security/PolicyJDK24.java
container/openejb-core/src/main/java/org/apache/openejb/core/security/jacc/BasicJaccProvider.java
server/openejb-client/src/main/java/org/apache/openejb/client/JaasIdentityResolver.java
server/openejb-client/src/main/java/org/apache/openejb/client/util/JDK24Subject.java
server/openejb-client/src/test/java/org/apache/openejb/client/MainTest.java

Support Java 24 at Runtime at the cost of loosing EJB Method Security, which does not work due to the deprecation / removal of SecurityManager in Java 21+ anyway.
Other suggestion to deal with it are very welcome ;-)
https://ci-builds.apache.org/job/Tomee/job/pull-request-manual/163/

TOMEE-4474 - TomEE does not launch on Java 24
